// This file is part of RoT MoE.
// SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
// Copyright 2026 Saimonokuma.
//
// =============================================================================
// PER-LANE SCORING OF THE A/B CORPUS
//
// Why this is a FILE and not a `node -e` inside ab-analyze.sh: the inline form
// was generated by a script, so an escape sequence passed through three levels
// -- generator string, shell heredoc, node argument -- and each level consumed
// one backslash. `split("\n")` arrived at node as a literal newline inside a
// string and died with a SyntaxError. That is the second time in one session an
// escaping level produced a broken artifact (the first turned mutation needles
// into literal backslash-n and scored nine DISCARDED).
//
// The fix is not more backslashes. It is one less level of nesting.
//
// WHAT IT COMPUTES. lean/Proofs/RotAttribute.lean proves on a checked instance
// that a pooled comparison can contradict every stratum it is made of
// (`pooling_reverses_every_stratum`), and that the reversal is driven by
// unequal stratum sizes (`balanced_pooling_agrees_with_the_strata`). This
// corpus has lanes of size 0 to 36, which is exactly that shape -- so the
// per-lane table is not a nicety, it is the only reading the theorem permits.
//
// WHAT IT DOES NOT COMPUTE: answer quality. Nothing here does, and no proxy is
// substituted for it.
//
// argv[2] = lane label file (TSV: turn <tab> lane)
// argv[3] = bench/ab-metrics.jsonl
// exit 0 = every lane covered · 7 = a lane has no prompt · 1 = bad input
// =============================================================================
"use strict";
const fs = require("fs");

const laneFile = process.argv[2];
const metricsFile = process.argv[3];
if (!laneFile || !metricsFile) {
  console.log("  usage: ab-lanes.js <lane-tsv> <metrics-jsonl>");
  process.exit(1);
}

const lanes = {};
for (const line of fs.readFileSync(laneFile, "utf8").trim().split("\n")) {
  const parts = line.split("\t");
  lanes[Number(parts[0])] = parts[1];
}

const recs = fs.readFileSync(metricsFile, "utf8").trim().split("\n")
  .map((l) => JSON.parse(l));
const A = {}, B = {};
for (const r of recs) (r.arm === "a" ? A : B)[r.turn] = r;

// Exact binomial, two-sided. BigInt so 80 choose 40 is not a float.
const choose = (n, k) => {
  let r = 1n;
  for (let i = 0n; i < BigInt(k); i++) { r = r * BigInt(n) - r * i; r = r / (i + 1n); }
  return r;
};
const signP = (w, n) => {
  let tail = 0n;
  const m = Math.max(w, n - w);
  for (let k = m; k <= n; k++) tail += choose(n, k);
  return Number(tail * 2n * 10n ** 12n / (2n ** BigInt(n))) / 1e12;
};

const by = {};
for (const key of Object.keys(A)) {
  const t = Number(key);
  if (!B[t]) continue;
  const L = lanes[t] || "UNLABELLED";
  const o = by[L] || (by[L] = { n: 0, aT: 0, bT: 0, aC: 0, bC: 0, win: 0, loss: 0 });
  o.n++;
  o.aT += A[t].outTok; o.bT += B[t].outTok;
  o.aC += A[t].cost_micro; o.bC += B[t].cost_micro;
  if (A[t].outTok < B[t].outTok) o.win++;
  else if (A[t].outTok > B[t].outTok) o.loss++;
}

console.log("  lane".padEnd(14) + "n".padStart(4) + "routed".padStart(9) +
  "ctrl".padStart(8) + "delta".padStart(9) + "  fewer".padStart(9) + "   sign p");
let favour = 0, total = 0;
const rows = Object.entries(by).sort((x, y) => y[1].n - x[1].n);
for (const [L, o] of rows) {
  const ma = o.aT / o.n, mb = o.bT / o.n;
  const d = mb === 0 ? 0 : (ma - mb) / mb * 100;
  total++;
  if (ma < mb) favour++;
  console.log("  " + L.padEnd(14) + String(o.n).padStart(4) +
    ma.toFixed(0).padStart(9) + mb.toFixed(0).padStart(8) +
    (d.toFixed(1) + "%").padStart(9) + ("  " + o.win + "/" + o.n).padStart(9) +
    "   " + signP(o.win, o.n).toExponential(2));
}

// THE LANE-LEVEL SIGN TEST. Several lanes hold four turns and cannot reach
// significance on their own; what they can do is AGREE. Under the null that
// each lane is a coin flip, all N agreeing has two-sided probability 2^-(N-1).
// This is a weaker claim than a per-lane result and is labelled as such.
const lanePr = Math.pow(2, -(total - 1));
console.log("");
console.log("  lanes favouring routed: " + favour + " of " + total +
  "   lane-level sign test p = " + lanePr.toExponential(2));

// COVERAGE IS PART OF THE RESULT, NEVER A FOOTNOTE. The router defines these
// lanes; a lane with no prompt is an ability that was NOT scored, and a claim
// that ranges over it would be an overclaim. Read from the router's own source
// rather than typed here, so a tenth lane cannot be silently ignored.
const routerSrc = fs.readFileSync(__dirname + "/../hooks/rot-router.sh", "utf8");
const declared = new Set();
const re = /LANE=(?:")?([A-Z]{4,12})(?:")?/g;
let m;
while ((m = re.exec(routerSrc)) !== null) declared.add(m[1]);
const known = declared.size >= 5
  ? Array.from(declared)
  : ["CONVERGENT", "CLINICAL", "EXECUTIVE", "EMPATHIC", "STRATEGIC",
     "CREATIVE", "PREDICTIVE", "STEALTH", "RECURSIVE", "FORGE"];
const missing = known.filter((L) => !(L in by)).sort();
console.log("  lanes declared by the router: " + known.length +
  "   scored here: " + total);
console.log("  lanes with NO prompt in the corpus: " +
  (missing.length ? missing.join(", ") : "none"));
process.exit(missing.length ? 7 : 0);
