#!/usr/bin/env bash
# This file is part of RoT MoE.
# SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
# Copyright 2026 Saimonokuma.
#
# =============================================================================
# THE BENCHMARK -- what the router COSTS and what it DELIVERS, in numbers a
# reader can re-derive by running this file.
#
# A plugin that sits in front of every turn owes its user three answers, and
# "it feels better" is none of them:
#
#   1. WHAT DOES IT COST?     milliseconds added per turn, measured over N runs.
#   2. DOES IT DECIDE WELL?   routing accuracy on a LABELLED corpus, where the
#                             expected lane was written down before the run.
#   3. DOES IT ACTUALLY FIRE? armed vs disarmed emissions in a REAL `claude`
#                             session -- the A/B that no unit test can fake.
#
# WHAT THIS BENCHMARK DELIBERATELY DOES NOT MEASURE, said here rather than
# discovered by a disappointed reader: whether the answers are BETTER. Output
# quality is not measurable on this machine, it is not measurable by any script
# in this repository, and a number claiming it would be invented. The honest
# scope is cost, decision quality against a written key, and attribution.
#
# Exit: 0 benchmark complete · 1 a measured property FAILED its bound ·
#       2 refuse · 3 SKIP (a phase could not run; never a pass).
# =============================================================================

set -uo pipefail

# --- a bound that does not assume GNU coreutils ------------------------------
# macOS does NOT ship `timeout` (it is GNU coreutils). A bare `timeout N cmd` is
# "command not found" there, which returns an EMPTY capture -- and an empty
# capture reads exactly like a tool that answered nothing. Homebrew installs the
# same binary as `gtimeout`. If neither exists the call runs UNBOUNDED, and that
# is announced rather than hidden. Full story: checker/release-install.sh.
if command -v timeout >/dev/null 2>&1; then TMOBIN=timeout
elif command -v gtimeout >/dev/null 2>&1; then TMOBIN=gtimeout
else TMOBIN=""; fi
run_bounded () {   # run_bounded <seconds> <cmd...>; reads stdin like the command it wraps
  _secs="$1"; shift
  if [ -n "$TMOBIN" ]; then "$TMOBIN" "$_secs" "$@"; else
    [ -n "${_unbounded_warned:-}" ] || { printf "  ----  UNBOUNDED: no timeout/gtimeout on PATH; a hang cannot be detected here\n" >&2; _unbounded_warned=1; }
    "$@"
  fi
}
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

PASS=0; FAIL=0
ok  () { printf '  PASS  %s\n' "$*"; PASS=$((PASS+1)); }
bad () { printf '  FAIL  %s\n' "$*"; FAIL=$((FAIL+1)); }
note() { printf '  ----  %s\n' "$*"; }

ROUTER="hooks/rot-router.sh"
[ -f "$ROUTER" ] || { echo "REFUSE: $ROUTER missing"; exit 2; }

# ---------------------------------------------------------------------------
echo "== 1. DECISION QUALITY -- a labelled key written before the run"
# ---------------------------------------------------------------------------
# The key is here, in the open, so anyone can dispute a label. A benchmark whose
# ground truth is generated by the thing being benchmarked measures nothing.
KEY=$(cat <<'EOF'
lake build the theorem and fix the sorry|FORGE
run the installer and deploy it|FORGE
debug this segfault, the test suite is red|CLINICAL
audit the crypto for a CVE|CLINICAL
decide urgently, no more delay|EXECUTIVE
give me a direct answer, no hedging|EXECUTIVE
I feel lost and tired lately|EMPATHIC
this story about my grandmother makes me cry|EMPATHIC
plan the roadmap and prioritise the legal work|STRATEGIC
analyse the strategy for next quarter|STRATEGIC
invent something surreal, embrace the chaos|CREATIVE
what does the paradox dream of|CREATIVE
predict the trend for the next horizon|PREDICTIVE
what is the likely future scenario|PREDICTIVE
compress this to fewer tokens|STEALTH
optimise the byte encoding|STEALTH
refactor the meta architecture recursively|RECURSIVE
how should this ontology evolve|RECURSIVE
EOF
)
total=0; hit=0; miss=""
while IFS='|' read -r prompt want; do
  [ -z "${prompt:-}" ] && continue
  total=$((total+1))
  got=$(printf '{"prompt":"%s"}' "$prompt" | run_bounded 20 bash "$ROUTER" 2>/dev/null \
        | sed -n 's/.*TIER 1 -> \([A-Z]*\).*/\1/p')
  if [ "$got" = "$want" ]; then hit=$((hit+1)); else miss="$miss
    want=$want got=${got:-<none>}  <- $prompt"; fi
done <<EOF
$KEY
EOF
pct=$(awk -v h="$hit" -v t="$total" 'BEGIN{ if(t>0) printf "%.1f", 100*h/t; else print "0" }')
note "routing accuracy: $hit/$total = ${pct}% on the labelled key above"
if [ "$hit" -eq "$total" ]; then
  ok "every labelled prompt reached its intended lane"
else
  bad "routing missed $((total-hit)) of $total:$miss"
fi

# A key that only ever asks for one lane would score 100% against a router that
# always answers FORGE. Coverage is part of the measurement, not a footnote.
lanes=$(printf '%s\n' "$KEY" | cut -d'|' -f2 | sort -u | grep -c .)
if [ "$lanes" -ge 8 ]; then
  ok "the key covers $lanes distinct lanes -- a constant router cannot score well on it"
else
  bad "the key covers only $lanes lanes; too few to distinguish a router from a constant"
fi

# ---------------------------------------------------------------------------
echo
echo "== 1b. PRIORITY -- what happens when a prompt matches TWO lanes"
# ---------------------------------------------------------------------------
# THIS PHASE EXISTS BECAUSE THE BENCHMARK CAUGHT ME, on its first run. The key
# above originally contained
#
#     decide now, we ship today   ->  labelled EXECUTIVE
#
# and the router answered FORGE. The router was RIGHT and the label was wrong:
# `ship` is a FORGE stem, and FORGE is evaluated FIRST. That order is not an
# accident of the `case` statement -- it is the contract, and `route_exact` in
# lean/Proofs/RotRoute.lean characterises all ten lanes in both directions, so
# reordering them breaks a theorem rather than merely changing behaviour.
#
# Deleting the awkward row would have hidden the most interesting property the
# benchmark can show, so it is measured explicitly instead: a prompt matching
# two lanes resolves to the HIGHER-priority one, deterministically.
amb=0
check_priority () {   # check_priority <prompt> <expected> <why>
  got=$(printf '{"prompt":"%s"}' "$1" | run_bounded 20 bash "$ROUTER" 2>/dev/null \
        | sed -n 's/.*TIER 1 -> \([A-Z]*\).*/\1/p')
  if [ "$got" = "$2" ]; then
    note "\"$1\" -> $got   ($3)"
  else
    bad "priority: \"$1\" -> ${got:-<none>}, expected $2 ($3)"
    amb=1
  fi
}
check_priority "decide now, we ship today"        FORGE    "FORGE beats EXECUTIVE: 'ship' is a FORGE stem"
check_priority "debug this and then ship it"      FORGE    "FORGE beats CLINICAL"
check_priority "I feel lost, please debug me"     CLINICAL "CLINICAL beats EMPATHIC"
[ "$amb" -eq 0 ] && ok "ambiguous prompts resolve by the proved priority order, deterministically"

# ---------------------------------------------------------------------------
echo
echo "== 2. COST -- milliseconds this adds to a turn"
# ---------------------------------------------------------------------------
N=20
start=$(date +%s%N 2>/dev/null || echo "")
if [ -z "$start" ]; then
  note "nanosecond clock unavailable; cost phase SKIPPED (never a pass)"
else
  i=0
  while [ "$i" -lt "$N" ]; do
    printf '{"prompt":"lake build the theorem"}' | bash "$ROUTER" >/dev/null 2>&1
    i=$((i+1))
  done
  end=$(date +%s%N)
  per=$(awk -v a="$start" -v b="$end" -v n="$N" 'BEGIN{ printf "%.1f", (b-a)/1000000/n }')
  note "router: ${per} ms per invocation, mean of $N runs (includes bash process start)"
  # The bound is deliberately generous and stated as a BOUND, not a target: what
  # matters to a user is that the hook is not perceptible next to a model call
  # measured in seconds. If this ever fails, the router got slow enough to
  # notice, which is the only thing worth alarming on.
  if awk -v p="$per" 'BEGIN{ exit !(p < 500) }'; then
    ok "per-turn cost is under the 500 ms bound (${per} ms)"
  else
    bad "per-turn cost ${per} ms exceeds the 500 ms bound -- a user would feel this"
  fi
  # Honest denominator: how much of that is bash itself, not our code.
  s2=$(date +%s%N); j=0
  while [ "$j" -lt "$N" ]; do bash -c ':' >/dev/null 2>&1; j=$((j+1)); done
  e2=$(date +%s%N)
  base=$(awk -v a="$s2" -v b="$e2" -v n="$N" 'BEGIN{ printf "%.1f", (b-a)/1000000/n }')
  note "of which ~${base} ms is bash process startup on this machine -- our logic is the remainder"
fi

# ---------------------------------------------------------------------------
echo
echo "== 3. ATTRIBUTION -- armed vs disarmed, in a real claude session"
# ---------------------------------------------------------------------------
# The A/B lives in checker/live-session-smoke.sh, which arms a SCRATCH config
# dir, runs `claude -p --debug hooks`, and requires the router's line to be
# PRESENT armed and ABSENT disarmed. It is delegated rather than duplicated: two
# implementations of the same test is two places for it to drift.
if command -v claude >/dev/null 2>&1; then
  note "claude CLI present -- delegating the A/B to checker/live-session-smoke.sh"
  note "(run it directly; it is a --full gate and takes minutes)"
  ok "the live A/B is available on this machine"
else
  note "claude CLI absent -- the live A/B cannot run here."
  note "This phase is SKIPPED and a skip is NEVER a pass."
fi

# ---------------------------------------------------------------------------
echo
echo "== 4. THE README DIAGRAM -- it must report THIS run, not a memory of one"
# ---------------------------------------------------------------------------
# A benchmark diagram in a README is decoration until something FAILS when it
# drifts. The numbers below are the ones phase 1 just COMPUTED, not constants
# retyped here: if the key grows a lane or a case, this phase demands the README
# move in the same edit.
#
# Deliberately NOT checked: the latency figure. It varies run to run (133.2 ms
# and 138.0 ms, measured minutes apart on one machine), so pinning it would turn
# a CORRECT README red -- the exact defect this project calls a spec that
# forbids a correct future. The README states the BOUND; the BOUND is bound.
RM="README.md"
if [ ! -f "$RM" ]; then
  bad "README.md not found -- the diagram cannot be bound to the benchmark"
else
  rm_fail=0
  grep -q "[*][*]$hit/$total[*][*]" "$RM" || { rm_fail=1; note "README does not carry the score $hit/$total"; }
  grep -q "$lanes lanes" "$RM"       || { rm_fail=1; note "README does not carry the lane count $lanes"; }
  grep -q "500 ms" "$RM"             || { rm_fail=1; note "README does not state the 500 ms bound this gate enforces"; }
  grep -q '```mermaid' "$RM"       || { rm_fail=1; note "README has no mermaid diagram block"; }
  grep -q "CLAIM" "$RM"              || { rm_fail=1; note "README does not separate CLAIM from MEASURED"; }
  if [ "$rm_fail" -eq 0 ]; then
    ok "the README diagram carries THIS run's numbers ($hit/$total, $lanes lanes, 500 ms bound)"
  else
    bad "the README benchmark diagram has drifted from the benchmark -- move them together"
  fi

  # -- controls: the phase must be able to fail, and must not always fail --
  probe="$(mktemp)"
  sed "s|[*][*]$hit/$total[*][*]|**999/999**|" "$RM" > "$probe"; src=$?
  if [ "$src" -ne 0 ] || [ ! -s "$probe" ]; then
    bad "CONTROL DID NOT APPLY: sed exit $src / empty mutant -- discarded, NOT survived"
  elif cmp -s "$probe" "$RM"; then
    bad "CONTROL DID NOT APPLY: the mutated copy is identical -- discarded, NOT survived"
  elif grep -q "[*][*]$hit/$total[*][*]" "$probe"; then
    bad "CONTROL: a README with the wrong score was still accepted"
  else
    ok "CONTROL: a README whose case total is wrong IS rejected -- the check can fail"
  fi
  rm -f "$probe"

  # -- 4b. the lane -> lens rows must match the ROUTER SOURCE ----------------
  # The README names a lens beside every lane. That is a claim about this code,
  # so it is read out of hooks/rot-router.sh rather than trusted: rename a lens
  # in the router and the README goes red in the same run.
  #
  # This extraction used to be `sed -n '70,78p'` -- a HARDCODED LINE RANGE. It
  # broke the moment a function was inserted above the route block: the range
  # still existed, still produced output, and the checker reported "0 lane->lens
  # pairs parsed" on a router that was perfectly correct. That is the fragile
  # spec this repository keeps warning about, found in its own checker: a
  # snapshot of where the code sat on the day it was written, red on a correct
  # change. It now matches the PATTERN of a lane emission anywhere in the file,
  # so moving code around cannot break it.
  #
  # The CONVERGENT branch deliberately does not match: it emits the convening
  # MODEL, not a lens, and there is no lens to check it against.
  lens_fail=0; lens_rows=0
  while read -r lane lens; do
    [ -z "${lane:-}" ] && continue
    lens_rows=$((lens_rows+1))
    # the README row for this lane must mention its lens (Violet -> Violet_Noir
    # etc, so the router token must appear as a prefix of the README's name)
    # Compare IDENTITY, not punctuation: the README renders "Anti-Venom" and
    # "Violet_Noir" for readability while the router token is "AntiVenom" and
    # "Violet". Stripping non-alphanumerics from the README row and requiring
    # the router token as a substring checks the thing that matters -- that the
    # named lens IS the one the code routes to -- without freezing a house
    # style that a future edit is entitled to change.
    if ! grep -E "\`$lane\`" "$RM" | tr -cd '[:alnum:]' | grep -qi "$lens"; then
      lens_fail=1; note "README lane $lane does not name its router lens $lens"
    fi
  done <<INNER
$(sed -n 's/.*echo "\([A-Z][A-Z]*\) \([A-Za-z][A-Za-z]*\)".*/\1 \2/p' "$ROUTER")
INNER
  # -- control: rename a lens in a COPY of the README and it must be caught.
  # Without this, "9 rows match" could mean the matcher accepts anything.
  lprobe="$(mktemp)"
  sed 's/[*][*]Claude[*][*]/**Fabricated**/' "$RM" > "$lprobe"; lrc=$?
  if [ "$lrc" -ne 0 ] || [ ! -s "$lprobe" ]; then
    bad "CONTROL DID NOT APPLY: sed exit $lrc / empty mutant -- discarded, NOT survived"
  elif cmp -s "$lprobe" "$RM"; then
    bad "CONTROL DID NOT APPLY: the lens rename changed nothing -- discarded, NOT survived"
  elif grep -E '\`FORGE\`' "$lprobe" | tr -cd '[:alnum:]' | grep -qi 'Claude'; then
    bad "CONTROL: a README whose FORGE lens was renamed still passed -- the matcher is blind"
  else
    ok "CONTROL: a renamed lens IS caught -- the lane->lens check can fail"
  fi
  rm -f "$lprobe"

  if [ "$lens_rows" -lt 9 ]; then
    bad "only $lens_rows lane->lens pair(s) parsed from $ROUTER -- the probe broke, not the README"
  elif [ "$lens_fail" -eq 0 ]; then
    ok "all $lens_rows lane->lens rows in the README match $ROUTER"
  else
    bad "the README lane->lens table has drifted from $ROUTER"
  fi
  if grep -q "[*][*]$hit/$total[*][*]" "$RM"; then
    ok "CONTROL: the real README passes that same predicate -- it is not always-fail"
  else
    bad "CONTROL: the predicate rejects the real README -- always-fail proves nothing"
  fi
fi


echo
echo "== 5. THE DEBUG LOG -- is the reported R/s+ REPRODUCIBLE, or just asserted?"
# ---------------------------------------------------------------------------
# WHY THIS PHASE EXISTS. Every earlier phase checks what the router DECIDED.
# None of them checks how it arrived there, because until now the router only
# emitted a one-line summary -- and a summary cannot show you that lens 5 was
# multiplied by the wrong mu, that a lens never participated, or that K silently
# fell to 8. Those are exactly the defects that leave the headline number
# looking plausible.
#
# ROTMOE_DEBUG_LOG makes the router append one JSON line per gauge evaluation
# carrying EVERY factor of the sum: per lens its lambda, mu, activity, delta,
# sigma, H and resulting term. This phase then does the only thing that turns a
# log into evidence: it recomputes R/s+ from those terms and requires the result
# to match what the router reported. If the log and the headline ever disagree,
# one of them is lying and this fails.
#
# The negative control matters as much as the check: a corrupted term MUST be
# caught, or the recomputation is arithmetic theatre.
_dbg="${TMPDIR:-/tmp}/rot-bench-debug.$$.jsonl"
rm -f "$_dbg"

ROTMOE_DEBUG_LOG="$_dbg" sh "$REPO/hooks/rot-router.sh" --route "lake build a theorem" >/dev/null 2>&1
ROTMOE_DEBUG_LOG="$_dbg" sh "$REPO/hooks/rot-router.sh" --vector 1,0,0,0,0,0,0,0,0 --breadth 1 >/dev/null 2>&1
ROTMOE_DEBUG_LOG="$_dbg" sh "$REPO/hooks/rot-router.sh" --vector 1,1,0,0,0,0,0,1,1 --breadth 4 >/dev/null 2>&1

if [ ! -s "$_dbg" ]; then
  bad "the debug log is EMPTY -- ROTMOE_DEBUG_LOG wrote nothing, so nothing below was tested"
else
  _n=$(grep -c '"kind":"gauge"' "$_dbg" 2>/dev/null || echo 0)
  if [ "$_n" -lt 2 ]; then
    bad "only $_n gauge records logged; expected one per gauge evaluation"
  else
    ok "the debug log records every gauge evaluation ($_n records)"
  fi

  # Every record must carry all nine lenses and K=9. A record with eight is the
  # "a lens silently stopped participating" bug, which is invisible in the
  # headline number and obvious here.
  _bad=$(awk '/"kind":"gauge"/ {
      k = 0; if (match($0, /"K":[0-9]+/)) { k = substr($0, RSTART+4, RLENGTH-4) + 0 }
      n = gsub(/"lens":/, "&");
      if (k != 9 || n != 9) c++
    } END { print c+0 }' "$_dbg")
  if [ "$_bad" -eq 0 ]; then
    ok "every record carries K=9 and nine per-lens terms -- no lens dropped out"
  else
    bad "$_bad record(s) had K != 9 or fewer than nine lens terms"
  fi

  # THE RECOMPUTATION. Sum the logged per-lens terms, divide by K, compare with
  # the logged Rs. Tolerance 1e-4 because both sides are printed decimals.
  _mis=$(awk '/"kind":"gauge"/ {
      sum = 0; s = $0;
      while (match(s, /"term":-?[0-9.]+/)) {
        sum += substr(s, RSTART+7, RLENGTH-7) + 0;
        s = substr(s, RSTART+RLENGTH);
      }
      k = 9; if (match($0, /"K":[0-9]+/)) { k = substr($0, RSTART+4, RLENGTH-4) + 0 }
      rs = 0; if (match($0, /"Rs":-?[0-9.]+/)) { rs = substr($0, RSTART+5, RLENGTH-5) + 0 }
      d = sum/k - rs; if (d < 0) d = -d;
      if (d > 0.0001) c++
    } END { print c+0 }' "$_dbg")
  if [ "$_mis" -eq 0 ]; then
    ok "R/s+ recomputed by hand from the per-lens terms matches the router, every record"
  else
    bad "$_mis record(s) where the logged R/s+ does NOT equal the sum of its own terms"
  fi

  # CONTROL: corrupt one term and require the recomputation to notice. Without
  # this, the check above could be passing because it always passes.
  _ctl="${TMPDIR:-/tmp}/rot-bench-debug-ctl.$$.jsonl"
  sed 's/"term":[0-9.]*/"term":99.0/' "$_dbg" > "$_ctl"
  _cmis=$(awk '/"kind":"gauge"/ {
      sum = 0; s = $0;
      while (match(s, /"term":-?[0-9.]+/)) {
        sum += substr(s, RSTART+7, RLENGTH-7) + 0;
        s = substr(s, RSTART+RLENGTH);
      }
      k = 9; if (match($0, /"K":[0-9]+/)) { k = substr($0, RSTART+4, RLENGTH-4) + 0 }
      rs = 0; if (match($0, /"Rs":-?[0-9.]+/)) { rs = substr($0, RSTART+5, RLENGTH-5) + 0 }
      d = sum/k - rs; if (d < 0) d = -d;
      if (d > 0.0001) c++
    } END { print c+0 }' "$_ctl")
  if [ "$_cmis" -gt 0 ]; then
    ok "CONTROL: a corrupted term IS caught ($_cmis record(s)) -- the recomputation can fail"
  else
    bad "CONTROL DID NOT FAIL: corrupting every term changed nothing, so this phase proves nothing"
  fi
  rm -f "$_ctl"

  # The log must never contain the prompt text. A debug log people are afraid to
  # paste is a debug log nobody uses.
  if grep -q '"prompt"' "$_dbg" 2>/dev/null; then
    bad "the debug log contains prompt text -- it must record chars, not content"
  else
    ok "the log records prompt LENGTH, never prompt text -- safe to paste into an issue"
  fi
fi
rm -f "$_dbg"

# ---------------------------------------------------------------------------
echo
echo "== 6. THE TWO ARMS -- which cost does the README actually quote?"
# ---------------------------------------------------------------------------
# WHY THIS PHASE EXISTS, and it is a misattribution I shipped.
#
# Phase 2 times the SHELL arm, because that is the arm a Linux CI runner has.
# The README then quoted that number as "the per-turn cost". But on Windows --
# where this plugin is developed and where the router is registered through
# hooks.json -- the arm that actually executes is `hooks/rot-router.ps1`. A live
# 56-turn session logged 93-133 ms (mean 104.6) while the bash arm benchmarks at
# 194-256 ms. Same router, same decisions, roughly half the cost, and the README
# was attributing the slower figure to the faster path.
#
# Neither number is wrong. Quoting one of them WITHOUT SAYING WHICH ARM is what
# is wrong, because a reader on Windows plans around a cost they will not pay,
# and a reader on Linux plans around one they will. So this phase measures both
# on the same prompt and requires the README to name the arm it is quoting.
#
# The PowerShell arm is environment-bound: no pwsh on a Linux runner is a SKIP,
# never a pass, and the phase says so out loud rather than silently passing.
PS_ARM="hooks/rot-router.ps1"
PSH=""
for cand in pwsh powershell; do
  command -v "$cand" >/dev/null 2>&1 && { PSH="$cand"; break; }
done

_sh_ms=""; _ps_ms=""
if [ -n "${start:-}" ] && [ -n "${per:-}" ]; then
  _sh_ms="$per"
  note "sh  arm: ${_sh_ms} ms per invocation (phase 2, mean of $N)"
fi

if [ -z "$PSH" ]; then
  note "SKIP: no pwsh/powershell on PATH -- the .ps1 arm's cost is UNMEASURED here"
  note "      (a skip is never a pass; the Windows figure must come from a real run)"
elif [ ! -f "$PS_ARM" ]; then
  bad "$PS_ARM is missing -- the arm half the users run does not exist"
else
  M=10
  _armlog="$(mktemp "${TMPDIR:-/tmp}/armcost.XXXXXX")"
  rm -f "$_armlog"
  ps_start=$(date +%s%N)
  k=0
  while [ "$k" -lt "$M" ]; do
    printf '{"prompt":"lake build the theorem"}' \
      | ROTMOE_DEBUG_LOG="$_armlog" "$PSH" -NoProfile -ExecutionPolicy Bypass \
        -File "$PS_ARM" >/dev/null 2>&1
    k=$((k+1))
  done
  ps_end=$(date +%s%N)
  _ps_ms=$(awk -v a="$ps_start" -v b="$ps_end" -v n="$M" 'BEGIN{ printf "%.1f", (b-a)/1000000/n }')
  note "ps1 arm: ${_ps_ms} ms per invocation WALL CLOCK, mean of $M (includes pwsh start)"

  # -------------------------------------------------------------------------
  # TWO TIMERS, AND THE MISTAKE OF COMPARING THEM. Measured 2026-08-01.
  #
  # The debug log's `ms` field starts at rot-router.ps1:40 -- INSIDE the script,
  # after the interpreter has already started. So it measures our LOGIC, not the
  # turn's cost. A live session logged 93-133 ms that way, and I compared it
  # against the shell arm's WALL-CLOCK figure and reported the .ps1 arm as
  # roughly half the cost. It is not. Measured like for like it is nearly
  # double, because PowerShell startup is ~159 ms against bash's ~20.
  #
  # Both numbers are real and both are useful; subtracting one from the other is
  # what produced a false statement. The phase now prints the decomposition so
  # the two can never again be quoted as if they were the same measurement.
  # -------------------------------------------------------------------------
  if [ -s "$_armlog" ]; then
    _inms=$(grep -o '"ms":[0-9]*' "$_armlog" | sed 's/"ms"://' \
      | awk '{s+=$1;n++} END{ if(n>0) printf "%.1f", s/n; else print "" }')
    if [ -n "$_inms" ]; then
      _startup=$(awk -v w="$_ps_ms" -v i="$_inms" 'BEGIN{ printf "%.1f", w-i }')
      note "ps1 arm: ${_inms} ms IN-SCRIPT (the router's own logic, what the debug log reports)"
      note "ps1 arm: ~${_startup} ms of the wall figure is PowerShell interpreter startup"
      if awk -v s="$_startup" 'BEGIN{ exit !(s > 0) }'; then
        ok "the two timers are decomposed: wall = in-script + interpreter startup"
      else
        bad "in-script time (${_inms}) exceeds wall time (${_ps_ms}) -- a timer is wrong"
      fi
    fi
  fi
  rm -f "$_armlog"
  # -------------------------------------------------------------------------
  # WHICH ARM DOES THE BOUND APPLY TO? Measured 2026-08-03, and the first
  # version of this phase got it wrong and failed CI for it.
  #
  # It bounded BOTH arms at 500 ms on every platform. On the Linux runner that
  # is 857.1 ms for the .ps1 arm -- of which 745.7 ms is pwsh starting up -- and
  # CI went red. But nothing on Linux ever invokes the .ps1 arm: hooks.json
  # dispatches to `rot-router.sh` there, which measured 38.2 ms on the same run.
  # The gate was enforcing a budget on a code path that platform never takes.
  #
  # The bound exists for one reason -- "a user would feel this" -- so it belongs
  # on the arm the user actually runs. The other arm is still MEASURED and
  # printed, because a cross-platform cost is worth knowing; it is simply not
  # grounds for failing a build on a machine where nobody pays it.
  #
  # This is NOT the bound being relaxed to make a red build green. The live arm
  # is still bounded at 500 ms on every platform, and phase 2 bounds the shell
  # arm unconditionally. What changed is WHICH measurement the bound is applied
  # to, and that is now determined by which arm the hook dispatches to here.
  # -------------------------------------------------------------------------
  case "$(uname -s 2>/dev/null)" in
    MINGW*|MSYS*|CYGWIN*|Windows_NT) _live_arm=ps1 ;;
    *)                               _live_arm=sh  ;;
  esac
  note "the arm that actually runs on this platform: $_live_arm"

  if [ "$_live_arm" = ps1 ]; then
    if awk -v p="$_ps_ms" 'BEGIN{ exit !(p < 500) }'; then
      ok "the LIVE arm (.ps1) is under the 500 ms bound (${_ps_ms} ms)"
    else
      bad "the LIVE arm (.ps1) costs ${_ps_ms} ms -- over the 500 ms bound"
    fi
  else
    note "the .ps1 arm measures ${_ps_ms} ms here, but .sh is the live arm on this"
    note "platform -- reported, NOT bounded, because no user pays this cost here"
    ok "the live arm on this platform (.sh) is bounded by phase 2, which passed"
  fi
  if [ -n "$_sh_ms" ]; then
    note "gap: sh ${_sh_ms} ms vs ps1 ${_ps_ms} ms on identical input"
  fi
fi

# THE BINDING. Whatever the numbers are, the README must not quote a per-turn
# cost without saying which arm produced it. This is the check that would have
# caught the misattribution, and it is stated over the property (an arm is
# named) rather than over today's figures (which move every run).
RMD="README.md"
if [ ! -f "$RMD" ]; then
  bad "README.md is missing -- the cost claim cannot be bound to anything"
else
  _costlines=$(grep -cE '[0-9]+(\.[0-9]+)? *ms' "$RMD")
  if [ "$_costlines" -eq 0 ]; then
    note "README quotes no millisecond figure -- nothing to misattribute"
  else
    _arm_named=$(grep -icE '(ps1|powershell|bash|sh arm|\.sh arm)' "$RMD")
    if [ "$_arm_named" -gt 0 ]; then
      ok "README names the arm alongside its $_costlines millisecond claim(s)"
    else
      bad "README quotes $_costlines ms figure(s) but never names WHICH ARM produced them"
    fi
    # And it must say which TIMER, not only which arm. An in-script figure and a
    # wall-clock figure differ here by ~159 ms of interpreter startup, and
    # quoting one as the other is the error this phase was written after making.
    _timer_named=$(grep -icE '(in-script|interpreter startup|process start)' "$RMD")
    if [ "$_timer_named" -gt 0 ]; then
      ok "README distinguishes in-script time from wall-clock (the interpreter startup, ~160 ms on Windows and ~750 ms for pwsh on Linux)"
    else
      bad "README quotes ms figures without saying whether interpreter startup is included"
    fi
  fi
  # CONTROL: the check must be able to fail. A README body with a cost and no
  # arm named must be flagged -- tested in memory, never on disk.
  _ctl_body="the hook adds 210 ms per turn."
  _ctl_arm=$(printf '%s' "$_ctl_body" | grep -icE '(ps1|powershell|bash|sh arm)')
  if [ "$_ctl_arm" -eq 0 ]; then
    ok "CONTROL: a cost claim with no arm named IS detectable"
  else
    bad "CONTROL DEAD: an unattributed cost claim was not detected"
  fi
fi

printf '\n== benchmark: %d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ] || exit 1
exit 0
