#!/usr/bin/env bash
# This file is part of RoT MoE.
# SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
# Copyright 2026 Saimonokuma.
#
# =============================================================================
# R3 / R13 -- bind the Lean model to the shipped hooks, and the hooks to each
# other.
#
# A proof that does not touch the shipped hook proves nothing about it. This
# executes BOTH REAL IMPLEMENTATIONS over one corpus and compares three things:
#
#   1. rot-router.sh  vs  rot-router.ps1     byte-for-byte on every row
#   2. either arm     vs  the Lean #eval corpus for the rows Lean fixes
#   3. either arm     vs  the LIVE readings measured from the running hook
#
# Comparison is on the FORMATTED STRING, not the number. That is deliberate:
# the locale trap (0.09 -> "0,09" under a comma-decimal locale) is invisible to
# a numeric comparison and fatal to the thing that consumes the output.
#
# Two implementations that agree is a truth a single green cannot fake -- a
# shared bug has to be written twice, in two languages, by hand. That is the
# entire argument for maintaining a second arm at all.
# =============================================================================


# THIS HARNESS DECLARES ITS OWN TRAFFIC.
#
# Measured 2026-08-09: seven checkers feed the router synthetic payloads and
# write into whatever ROTMOE_DEBUG_LOG points at. 738 of 955 sh route records
# in the live log were theirs, and nothing in the schema said so -- so every
# "live router health" figure computed from that log silently mixed real
# lifecycle traffic with replayed corpus traffic. The instrument was
# contaminating its own measurement and could not report that it was.
#
# RotSessionLog.test_is_never_hook proves the consequence: a record declared
# here can never be classified as live traffic, whatever the payload contains.
export ROTMOE_DEBUG_SRC=test

# Never write a per-session log into the repository being tested. A checker
# that leaves files behind is not a read-only observer.
export ROTMOE_DEBUG_LOCAL=0

set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
SH="$REPO/hooks/rot-router.sh"
PS1="$REPO/hooks/rot-router.ps1"
CORPUS="$REPO/checker/corpus-gauge.txt"

pass=0; fail=0; skip=0
ok()   { echo "  PASS  $*"; pass=$((pass+1)); }
bad()  { echo "  FAIL  $*"; [ "${GITHUB_ACTIONS:-}" = "true" ] && printf '::error title=cross-diff::%s\n' "$*"; fail=$((fail+1)); }
# A skipped comparison is neither a pass nor a failure, and saying so out loud is
# the point: without pwsh this file compares one arm against a corpus and calls
# it a cross-diff. It counts nothing, so it cannot inflate the pass total.
note() { echo "  ----  $*"; }

PWSH=""
for c in pwsh powershell; do command -v "$c" >/dev/null 2>&1 && { PWSH="$c"; break; }; done

# U1 (7.0.0): THE PROFILE GOLDEN. The ten-profile phase below was arm-vs-arm
# ONLY, so a digit changed in a non-FORGE weight table was cross-checked
# nowhere on a pwsh-less machine (H01's blind spot -- the corpus itself
# stays pinned to FORGE by Lean). The golden records the POSIX arm's one
# probe line per profile VERBATIM -- single lines, so the diff on failure is
# readable -- and holds them with or without a second arm. Regeneration is a
# deliberate act: `--make-golden` rewrites from the CURRENT arm, banner up.
GOLDENP="$REPO/checker/golden-gauge-profiles.txt"
_pvec='1,0,1,0,1,0,1,0,1'
_pbr=4
if [ "${1:-}" = "--make-golden" ]; then
  echo "== REGENERATING THE PROFILE GOLDEN -- a deliberate act =="
  {
    echo "# RoT MoE -- golden per-profile gauge lines (organ 2)."
    echo "# SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2"
    echo "# Copyright 2026 Saimonokuma."
    echo "# GENERATED by checker/cross-diff.sh --make-golden. Never hand-edit."
    echo "# One line per profile: PROFILE|<human line>|<gauge record lenses array>"
    echo "# The lenses array is the debug record's, at ITS precisions (lambda 3,"
    echo "# mu 3, term 5): the human line rounds R/s+ to 2 decimals, under which"
    echo "# a single table digit can hide -- MEASURED before this column existed:"
    echo "# CONVERGENT lambda 1.6->1.7 moved R by ~0.008 and the printed line"
    echo "# never flinched. The record arrays hold every digit verbatim."
  } > "$GOLDENP.tmp"
  _gtd=$(mktemp -d 2>/dev/null || echo "${TMPDIR:-/tmp}/cd-golden.$$"); mkdir -p "$_gtd"
  for _prof in CONVERGENT CLINICAL EXECUTIVE EMPATHIC STRATEGIC CREATIVE PREDICTIVE STEALTH RECURSIVE FORGE; do
    : > "$_gtd/g.jsonl"
    _gout=$(ROTMOE_DEBUG_LOG="$_gtd/g.jsonl" ROTMOE_DEBUG_SRC=test "$SH" --profile "$_prof" --vector "$_pvec" --breadth "$_pbr" --M 1 --C 1 --T 1)
    _glens=$(sed -n 's/.*"lenses":\[\(.*\)\]}.*/\1/p' "$_gtd/g.jsonl" | head -1)
    { [ -n "$_gout" ] && [ -n "$_glens" ]; } || { echo "REFUSE: profile $_prof produced no output or no gauge record -- a golden must be cut from a healthy arm"; rm -rf "$_gtd"; rm -f "$GOLDENP.tmp"; exit 2; }
    printf '%s|%s|%s\n' "$_prof" "$_gout" "$_glens" >> "$GOLDENP.tmp"
  done
  rm -rf "$_gtd"
  mv "$GOLDENP.tmp" "$GOLDENP"
  echo "   golden written: $GOLDENP (10 profiles, human line + full-precision lens array)"
  exit 0
fi

echo "== corpus =="
[ -f "$CORPUS" ] || { echo "FATAL: corpus missing: $CORPUS"; exit 2; }
echo "  $(grep -cvE '^\s*(#|$)' "$CORPUS") rows"
[ -n "$PWSH" ] && echo "  PowerShell: $PWSH" || echo "  PowerShell: ABSENT -- arm-vs-arm rows will be SKIPPED, not passed"

echo
echo "== 1+3: POSIX arm vs the expected string (Lean corpus / live readings) =="
while IFS='|' read -r vec br M C T want note; do
  case "$vec" in ''|\#*) continue ;; esac
  got=$("$SH" --profile FORGE --vector "$vec" --breadth "$br" --M "$M" --C "$C" --T "$T")
  if [ "$got" = "$want" ]; then ok "$note"
  else bad "$note"; echo "        want: $want"; echo "        got : $got"; fi
done < <(grep -vE '^\s*(#|$)' "$CORPUS")

echo
echo "== 2: cross-diff -- the two arms must agree BYTE FOR BYTE =="
if [ -z "$PWSH" ]; then
  echo "  SKIP  no PowerShell on this machine ($((`grep -cvE '^\s*(#|$)' "$CORPUS"`)) rows unverified)"
  skip=$((skip+1))
else
  while IFS='|' read -r vec br M C T want note; do
    case "$vec" in ''|\#*) continue ;; esac
    a=$("$SH" --profile FORGE --vector "$vec" --breadth "$br" --M "$M" --C "$C" --T "$T")
    b=$("$PWSH" -NoProfile -File "$PS1" -Profile FORGE -Vector "$vec" -Breadth "$br" -M "$M" -C "$C" -T "$T")
    b=$(printf '%s' "$b" | tr -d '\r')
    if [ "$a" = "$b" ]; then ok "arms agree: $note"
    else bad "ARMS DISAGREE: $note"; echo "        sh : $a"; echo "        ps1: $b"; fi
  done < <(grep -vE '^\s*(#|$)' "$CORPUS")
fi

echo
echo "== 2b: EVERY PROFILE across both arms -- not just FORGE =="
# THE 86 ROWS ABOVE ALL RUN UNDER `--profile FORGE`. That was correct when the
# router had ONE weight table and FORGE was its name. After profile switching it
# means the arms are compared in ONE of TEN profiles, and the other nine are
# cross-checked nowhere -- measured directly: a digit changed in the shell's
# CONVERGENT table left this checker at 86 passed, 0 failed.
#
# That is the same defect that had already been found in lean-binds-shell.sh
# (one table verified out of ten), arriving in a second checker, and it gives
# FORGE an authority over the other nine profiles that nothing in the spec
# grants it. Section 4 defines ten profiles as peers; CONVERGENT, not FORGE, is
# the documented default and the convener.
#
# The corpus stays pinned to FORGE -- Lean pins those exact strings, and
# re-pinning 86 rows x 10 profiles would be a different, slower instrument. This
# phase adds what was missing at proportionate cost: ONE probe per profile, both
# arms, byte-for-byte. Ten comparisons, twenty spawns, and no profile is
# privileged any more.
# U1: the POSIX arm runs every profile UNCONDITIONALLY now -- the golden
# holds it with no second arm, and pwsh adds the arm-vs-arm comparison on
# top where it exists. The discrimination CONTROL never needed pwsh at all
# and runs on every machine.
[ -z "$PWSH" ] && { echo "  SKIP  no PowerShell on this machine (arm-vs-arm profile rows unverified)"; skip=$((skip+1)); }
_gp_ok=''
if [ -f "$GOLDENP" ]; then _gp_ok=1
else
  echo "  SKIP  no profile golden -- single-arm profile drift is NOT held here."
  echo "        Generate deliberately: bash checker/cross-diff.sh --make-golden"
  skip=$((skip+1))
fi
_cdt=$(mktemp -d 2>/dev/null || echo "${TMPDIR:-/tmp}/cd-verify.$$"); mkdir -p "$_cdt"
for _prof in CONVERGENT CLINICAL EXECUTIVE EMPATHIC STRATEGIC CREATIVE PREDICTIVE STEALTH RECURSIVE FORGE; do
  : > "$_cdt/g.jsonl"
  a=$(ROTMOE_DEBUG_LOG="$_cdt/g.jsonl" ROTMOE_DEBUG_SRC=test "$SH" --profile "$_prof" --vector "$_pvec" --breadth "$_pbr" --M 1 --C 1 --T 1)
  al=$(sed -n 's/.*"lenses":\[\(.*\)\]}.*/\1/p' "$_cdt/g.jsonl" | head -1)
  if [ -z "$a" ]; then
    bad "profile $_prof: the POSIX arm produced NO OUTPUT -- this row measured nothing"
    continue
  fi
  if [ -n "$_gp_ok" ]; then
    wline=$(grep "^$_prof|" "$GOLDENP" | head -1)
    wrest=${wline#*|}; want=${wrest%%|*}; wantl=${wrest#*|}
    if [ -z "$wline" ]; then
      bad "profile $_prof has NO golden line -- stale golden; regenerate deliberately (--make-golden)"
    elif [ "$a" = "$want" ] && [ "$al" = "$wantl" ]; then
      ok "POSIX arm matches the golden under profile $_prof (line + full-precision lens array)"
    else
      bad "POSIX arm DIVERGES from the golden under profile $_prof"
      [ "$a" != "$want" ] && { echo "        live  : $a"; echo "        golden: $want"; }
      [ "$al" != "$wantl" ] && { echo "        live lenses  : $(printf '%s' "$al" | head -c 200)"; echo "        golden lenses: $(printf '%s' "$wantl" | head -c 200)"; }
    fi
  fi
  if [ -n "$PWSH" ]; then
    b=$("$PWSH" -NoProfile -File "$PS1" -Profile "$_prof" -Vector "$_pvec" -Breadth "$_pbr" -M 1 -C 1 -T 1)
    b=$(printf '%s' "$b" | tr -d '\r')
    if [ "$a" = "$b" ]; then ok "arms agree under profile $_prof: $a"
    else bad "ARMS DISAGREE under profile $_prof"; echo "        sh : $a"; echo "        ps1: $b"; fi
  fi
done
rm -rf "$_cdt" 2>/dev/null || :

# The phase must be able to TELL PROFILES APART, or ten identical passes would
# prove only that both arms ignore the flag. Two profiles whose weights differ
# must produce different readings on the same input. POSIX-only, so it runs
# on every machine.
_c1=$("$SH" --profile CONVERGENT --vector "$_pvec" --breadth "$_pbr" --M 1 --C 1 --T 1)
_c2=$("$SH" --profile STEALTH    --vector "$_pvec" --breadth "$_pbr" --M 1 --C 1 --T 1)
if [ "$_c1" != "$_c2" ]; then ok "CONTROL: CONVERGENT and STEALTH read differently, so this phase can discriminate"
else bad "CONTROL: every profile reads the same -- the flag is ignored and all ten rows above are vacuous"; fi

echo
echo "== TIER 1: both arms, every lane =="
# One probe per lane plus the default. This is the routing half of R7b: it
# executes the SHIPPED router, not the model. RotRoute.lean proves the order is
# total and dead-lane-free; this proves the shipped code implements that order.
# CONVERGENT names the MODEL that convenes the nine, not a lead lens, so its
# expected value depends on the machine's settings.json. Pinning the override
# makes the row deterministic on every machine WITHOUT weakening it: the check
# still asserts the exact string, it just asserts one the test controls. An
# expectation that quoted this developer's model would have been a snapshot,
# red on any other machine with nothing wrong.
ROTMOE_MODEL="ROTMOE_TESTMODEL"; export ROTMOE_MODEL

while IFS='|' read -r prompt want; do
  case "$prompt" in ''|\#*) continue ;; esac
  got=$("$SH" --route "$prompt")
  [ "$got" = "$want" ] && ok "sh route: '$prompt' -> $got" \
                       || { bad "sh route: '$prompt'"; echo "        want $want got $got"; }
  if [ -n "$PWSH" ]; then
    gp=$("$PWSH" -NoProfile -File "$PS1" -Route "$prompt" | tr -d '\r')
    [ "$gp" = "$got" ] && ok "arms agree on route: '$prompt'" \
                       || { bad "ROUTE ARMS DISAGREE: '$prompt'"; echo "        sh $got / ps1 $gp"; }
  fi
done <<'ROUTES'
lake build the theorem|FORGE Claude
fix this bug|CLINICAL AntiVenom
decide now|EXECUTIVE Venom
how do i feel|EMPATHIC Violet
plan the roadmap|STRATEGIC Nova
invent a paradox|CREATIVE Carnage
what happens next|PREDICTIVE Chroma
compress the tokens|STEALTH Soleil
refactor the meta layer|RECURSIVE Eidolon
hello there|CONVERGENT ROTMOE_TESTMODEL
# --- 0.7.0: the word-prefix matcher -----------------------------------------
# THE TWO PROMPTS THAT WERE MEASURED WRONG. Before the fix, on the shipped
# router: "prove this lemma" -> CONVERGENT, and the second -> STEALTH, because
# it matched `byte` and nothing in FORGE. On a prover head those are the two
# most proof-shaped prompts imaginable.
prove this lemma|FORGE Claude
prove the read loop conserves bytes in lean|FORGE Claude
# --- 6.0.2 (W6): the ideation vocabulary ------------------------------------
# Measured over thirty live turns: asks phrased the way people actually ask
# for creative work -- "brainstorm", "ideate", "imagine", "a tagline" --
# routed CONVERGENT because CREATIVE only knew its own nouns. These rows
# hold the four admitted stems; collisions were checked before admission.
brainstorm a tagline for the launch|CREATIVE Carnage
imagine an ideation exercise|CREATIVE Carnage
# THE COLLISIONS THAT MADE THOSE STEMS UNADDABLE. Each row is a word CONTAINING
# a stem: a substring matcher routes every one of them to FORGE, which is why
# `prove`, `lemma` and `lean` could not simply be appended to the list. These
# rows are the reason the matcher cannot be reverted quietly.
improve the documentation|CONVERGENT ROTMOE_TESTMODEL
that is the dilemma|CONVERGENT ROTMOE_TESTMODEL
cleaning up the tree|CONVERGENT ROTMOE_TESTMODEL
# COLLISIONS THAT WERE ALREADY LIVE before 0.7.0 and are fixed by the same rule:
# `fix` fired on "prefix", `now` on "known", `test` on "latest". Each of these
# used to reach a lane that has nothing to do with the prompt.
add a prefix to the name|CONVERGENT ROTMOE_TESTMODEL
what is known about it|CONVERGENT ROTMOE_TESTMODEL
the latest release notes|CONVERGENT ROTMOE_TESTMODEL
# AND THE PREFIXES THAT MUST STILL FIRE. A stem is a word PREFIX, not a whole
# word -- `verif` has always been expected to catch "verification". A matcher
# tightened to whole words would pass every row above and break these.
proofs of termination|FORGE Claude
verification of the bound|CLINICAL AntiVenom
the strategy document|STRATEGIC Nova
# THE PUNCTUATION-LED EXCEPTION: `.lean` has no word boundary before the dot, so
# it falls back to a substring test. Without that carve-out this row goes red.
check Basic.lean now|FORGE Claude
ROUTES

echo
echo "== THE TWO ARMS MUST AGREE ON *WHY*, NOT ONLY ON WHICH =="
# The loop above compares `--route` output, which prints the LANE alone. When the
# route record gained a `stem`, that comparison stopped covering the whole
# decision: the arms could record different reasons for the same lane and every
# check in this file would stay green. The gap was introduced by the same change
# that added the field, which is the usual way a cross-diff develops a blind
# spot -- the new observable is simply not in the old comparison.
#
# `--route` is deliberately NOT widened to print the stem: its output is compared
# byte for byte against a corpus and against the other arm, and changing it would
# be changing the thing under test. The stem is compared where it actually
# lives -- in the log, written by the real hook path, which also exercises the
# ps1 arm's `Split-Routed` that nothing else touches.
if [ -n "$PWSH" ]; then
  _SD="$(mktemp -d "${TMPDIR:-/tmp}/xdstem.XXXXXX")"
  _stem_of () {   # _stem_of <logfile> -> the route record's stem, or the string NONE
    if [ "$(grep -c '"kind":"route"' "$1")" -eq 0 ]; then printf 'NONE'; return; fi
    # One sed, no pipe. `... | head -1` would be the same SIGPIPE hazard rule 7
    # in workflow-lint exists to forbid: head exits at the first line, sed dies
    # of SIGPIPE, and under `pipefail` a SUCCESSFUL extraction reports 141. The
    # `q` does the truncation inside the one process instead.
    # Address block, not 's///p; /re/q' -- the latter cannot quit, because 's'
    # has already removed the text the 'q' address is looking for. Latent here
    # (these logs carry one route record) and it bit for real in the gauge
    # extractor below, which saw two.
    sed -n '/"kind":"route"/{s/.*"kind":"route".*"stem":"\([^"]*\)".*/\1/p;q;}' "$1"
  }
  _drive () {     # _drive <arm> <prompt> <logfile>
    rm -f "$3"
    if [ "$1" = sh ]; then
      printf '{"prompt":"%s"}' "$2" | ROTMOE_DEBUG_LOG="$3" "$SH" >/dev/null 2>&1
    else
      printf '{"prompt":"%s"}' "$2" | ROTMOE_DEBUG_LOG="$3" "$PWSH" -NoProfile -File "$PS1" >/dev/null 2>&1
    fi
  }
  _sdis=0; _srows=0
  for _p in "lake build the theorem" "fix this bug" "refactor the meta layer" \
            "compress this to fewer tokens" "some entirely unremarkable sentence"; do
    _drive sh  "$_p" "$_SD/a.log"
    _drive ps1 "$_p" "$_SD/b.log"
    _a=$(_stem_of "$_SD/a.log"); _b=$(_stem_of "$_SD/b.log")
    if [ "$_a" = "NONE" ] || [ "$_b" = "NONE" ]; then
      bad "STEM: no route record from one arm for '$_p' (sh=$_a ps1=$_b) -- nothing compared"
      _sdis=1
    elif [ "$_a" = "$_b" ]; then
      _srows=$((_srows+1))
      ok "arms agree on the reason: '$_p' -> stem '${_a:-<none, CONVERGENT>}'"
    else
      bad "STEM ARMS DISAGREE: '$_p' -- sh '$_a' / ps1 '$_b'"
      _sdis=1
    fi
  done
  # A row count guard, for the same reason bench-router carries one: a loop that
  # silently compared nothing would print no failures and read as agreement.
  [ "$_srows" -ge 5 ] || bad "only $_srows stem rows compared -- the probe broke, not the arms"
  # CONTROL: the comparison must be able to FAIL. Two DIFFERENT prompts are fed
  # to the two arms; their stems must differ and that difference must be seen.
  # This exercises the real extraction path, not the shell's `=` operator.
  _drive sh  "lake build the theorem"  "$_SD/a.log"
  _drive ps1 "compress this to fewer tokens" "$_SD/b.log"
  _a=$(_stem_of "$_SD/a.log"); _b=$(_stem_of "$_SD/b.log")
  if [ "$_a" != "NONE" ] && [ "$_b" != "NONE" ] && [ "$_a" != "$_b" ]; then
    ok "CONTROL: a genuine stem disagreement IS detected (sh '$_a' vs ps1 '$_b')"
  else
    bad "CONTROL: the stem comparison could not distinguish two different prompts (sh '$_a' ps1 '$_b')"
  fi
  rm -rf "$_SD"
else
  note "no pwsh: the stem cross-diff is SKIPPED, which is never a pass"
fi

echo
echo "== GAUGE PROVENANCE: the two fields this cross-diff never looked at =="
# THE BLIND SPOT THIS CLOSES, and it is the same one the stem block above
# describes: a new observable is added and simply is not in the old comparison.
#
# `src` and `session` live on the GAUGE record. Every comparison in this file
# reads the ROUTE record. So for the whole life of the two-log subsystem the
# arms could disagree about provenance and this checker stayed green -- and they
# did disagree, in the worst possible way: on the CLI path the POSIX arm wrote
# src="cli" while the PowerShell arm wrote src="" (an unset variable), and 228
# such records shipped. Neither arm was compared, so neither was caught.
#
# The CLI path matters specifically. `_drive` above only ever feeds a payload on
# stdin, so it exercises hook mode alone; `--vector` returns before hook mode is
# reached and was therefore never observed by any cross-arm check.
#
# Spec: resolveNow in lean/Proofs/RotSessionLog.lean.
#   src_declaration_wins_on_every_path  -- declared value wins, both paths
#   resolveNow_never_renders_empty      -- EMPTY is unreachable, every input
if [ -n "$PWSH" ]; then
  _GD="$(mktemp -d "${TMPDIR:-/tmp}/xdprov.XXXXXX")"

  # NONE (no gauge record) / ABSENT (no such field) / EMPTY (present but "") are
  # reported as three DIFFERENT strings on purpose. Collapsing them is how the
  # shipped defect stayed invisible: an empty value read as "nothing to compare"
  # rather than as a value no classifier can produce.
  _gfield () {   # _gfield <logfile> <field>
    if [ ! -f "$1" ]; then printf 'NONE'; return; fi
    if [ "$(grep -c '"kind":"gauge"' "$1" 2>/dev/null)" = "0" ]; then printf 'NONE'; return; fi
    if [ "$(grep -c "\"$2\":\"" "$1" 2>/dev/null)" = "0" ]; then printf 'ABSENT'; return; fi
    # THE ADDRESS BLOCK IS LOAD-BEARING. 's///p; /re/q' looks equivalent and
    # is not: 's' rewrites the pattern space, so by the time 'q' tests its
    # address the text it matched is gone, 'q' never fires, and a second record
    # prints too -- yielding a two-line value that compares unequal to itself.
    _v=$(sed -n "/\"kind\":\"gauge\"/{s/.*\"kind\":\"gauge\".*\"$2\":\"\([^\"]*\)\".*/\1/p;q;}" "$1")
    if [ -z "$_v" ]; then printf 'EMPTY'; else printf '%s' "$_v"; fi
  }

  # This checker exports ROTMOE_DEBUG_SRC=test, so "no declaration" must be
  # expressed with `env -u`. `${x:+...}` leaves the INHERITED value in place --
  # measured, and it silently turned six cells of the session-log phase G into
  # a test of nothing.
  _pdrive () {   # _pdrive <arm> <mode: hook|cli> <declaration|-> <logfile>
    rm -f "$4"
    if [ "$3" = '-' ]; then _e="-u ROTMOE_DEBUG_SRC"; else _e="ROTMOE_DEBUG_SRC=$3"; fi
    if [ "$2" = cli ]; then
      if [ "$1" = sh ]; then
        env $_e ROTMOE_DEBUG_LOG="$4" ROTMOE_DEBUG_LOCAL=0 "$SH" \
          --vector 0,0,0,0,0,0,0,0,1 --breadth 1 --M 1 --C 1 --T 1 >/dev/null 2>&1
      else
        env $_e ROTMOE_DEBUG_LOG="$4" ROTMOE_DEBUG_LOCAL=0 "$PWSH" -NoProfile -File "$PS1" \
          -Vector 0,0,0,0,0,0,0,0,1 -Breadth 1 -M 1 -C 1 -T 1 >/dev/null 2>&1
      fi
    else
      _pl='{"prompt":"lake build","hook_event_name":"UserPromptSubmit","session_id":"xd-9f2"}'
      if [ "$1" = sh ]; then
        printf '%s' "$_pl" | env $_e ROTMOE_DEBUG_LOG="$4" ROTMOE_DEBUG_LOCAL=0 \
          "$SH" >/dev/null 2>&1
      else
        printf '%s' "$_pl" | env $_e ROTMOE_DEBUG_LOG="$4" ROTMOE_DEBUG_LOCAL=0 \
          "$PWSH" -NoProfile -File "$PS1" >/dev/null 2>&1
      fi
    fi
  }

  _prows=0
  # mode  declaration  field    expected
  for _row in "cli  -     src      cli" \
              "cli  test  src      test" \
              "hook -     src      hook" \
              "hook test  src      test" \
              "hook -     session  xd-9f2"; do
    set -- $_row
    _m="$1"; _d="$2"; _f="$3"; _want="$4"
    _pdrive sh  "$_m" "$_d" "$_GD/a.log"
    _pdrive ps1 "$_m" "$_d" "$_GD/b.log"
    _a=$(_gfield "$_GD/a.log" "$_f"); _b=$(_gfield "$_GD/b.log" "$_f")
    if [ "$_a" != "$_b" ]; then
      bad "PROVENANCE ARMS DISAGREE: $_m decl=$_d $_f -- sh '$_a' / ps1 '$_b'"
    elif [ "$_a" != "$_want" ]; then
      bad "PROVENANCE WRONG IN BOTH ARMS: $_m decl=$_d $_f = '$_a', spec says '$_want'"
    else
      _prows=$((_prows+1))
      ok "arms agree and match the spec: $_m decl=$_d -> $_f='$_a'"
    fi
  done
  [ "$_prows" -ge 5 ] || bad "only $_prows provenance rows compared -- the probe broke, not the arms"

  # CONTROL 1: the comparison must SEE a real cross-arm disagreement. Two
  # different declarations are fed to the two arms; that must be reported.
  _pdrive sh  cli test "$_GD/a.log"
  _pdrive ps1 cli -    "$_GD/b.log"
  _a=$(_gfield "$_GD/a.log" src); _b=$(_gfield "$_GD/b.log" src)
  if [ "$_a" != "$_b" ]; then
    ok "CONTROL: a genuine provenance disagreement IS detected (sh '$_a' vs ps1 '$_b')"
  else
    bad "CONTROL DEAD: two different declarations read identically ('$_a') -- this phase proves nothing"
  fi

  # CONTROL 2: EMPTY must be distinguishable from a real value, or the exact
  # shipped defect would read as agreement. Planted, not produced -- the router
  # can no longer emit this, which is the point.
  printf '%s\n' '{"kind":"gauge","ts":"x","session":"unknown","src":"","K":9}' > "$_GD/c.log"
  if [ "$(_gfield "$_GD/c.log" src)" = "EMPTY" ]; then
    ok "CONTROL: a planted empty src reads as EMPTY, not as absent or as a value"
  else
    bad "CONTROL DEAD: a planted empty src read as '$(_gfield "$_GD/c.log" src)'"
  fi
  rm -rf "$_GD"
else
  note "no pwsh: the gauge-provenance cross-diff is SKIPPED, which is never a pass"
fi

echo
echo "== THE ANIMUS CONSUMPTION: one queue, two arms, one envelope =="
# The worker-side ear (8.0.0) is a NEW observable on the envelope path, and
# the lesson written all over this file is that a new observable left out of
# the comparison is where the arms drift unseen. Each arm gets its OWN state
# dir and an IDENTICALLY planted queue; the envelopes must agree byte for
# byte, and so must what remains of the queue afterwards. The refusal and
# the off-switch are compared too -- agreeing on when NOT to speak is half
# the contract.
if [ -n "$PWSH" ]; then
  _AD="$(mktemp -d "${TMPDIR:-/tmp}/xdanim.XXXXXX")"
  _apay='{"session_id":"xd-anim","hook_event_name":"PostToolUse","tool_name":"Bash","tool_input":{"command":"echo hi"},"tool_response":{"stdout":"hi","stderr":""}}'
  _adrive () {   # _adrive <arm> <statedir> [extra VAR=val...]
    _arm=$1; _sd=$2; shift 2
    if [ "$_arm" = sh ]; then
      printf '%s' "$_apay" | env "$@" ROTMOE_ANIMUS=1 ROTMOE_STATE_DIR="$_sd" ROTMOE_DEBUG_LOCAL=0 "$SH" 2>/dev/null
    else
      printf '%s' "$_apay" | env "$@" ROTMOE_ANIMUS=1 ROTMOE_STATE_DIR="$_sd" ROTMOE_DEBUG_LOCAL=0 "$PWSH" -NoProfile -File "$PS1" 2>/dev/null
    fi
  }
  mkdir -p "$_AD/a" "$_AD/b"

  # one remark: spoken identically, consumed identically
  printf 'AntiVenom|a planted animus remark\n' > "$_AD/a/animus-queue.xd-anim"
  printf 'AntiVenom|a planted animus remark\n' > "$_AD/b/animus-queue.xd-anim"
  _oa=$(_adrive sh  "$_AD/a"); _ob=$(_adrive ps1 "$_AD/b")
  if [ "$_oa" = "$_ob" ]; then
    case "$_oa" in
      *'AntiVenom (animus): a planted animus remark'*) ok "ANIMUS: both arms speak the remark on one identical envelope" ;;
      *) bad "ANIMUS: arms agree but neither spoke the remark: $_oa" ;;
    esac
  else
    bad "ANIMUS ARMS DISAGREE on the consumption envelope -- sh: $_oa / ps1: $_ob"
  fi
  if [ ! -f "$_AD/a/animus-queue.xd-anim" ] && [ ! -f "$_AD/b/animus-queue.xd-anim" ]; then
    ok "ANIMUS: both arms consumed the queue"
  else
    bad "ANIMUS: queue survival differs or both survived (sh: $(ls "$_AD/a" 2>/dev/null | tr '\n' ' ')/ ps1: $(ls "$_AD/b" 2>/dev/null | tr '\n' ' '))"
  fi

  # FIFO: same first remark spoken, same remainder left
  printf 'Venom|first remark\nSoleil|second remark\n' > "$_AD/a/animus-queue.xd-anim"
  printf 'Venom|first remark\nSoleil|second remark\n' > "$_AD/b/animus-queue.xd-anim"
  _oa=$(_adrive sh  "$_AD/a"); _ob=$(_adrive ps1 "$_AD/b")
  [ "$_oa" = "$_ob" ] && ok "ANIMUS: FIFO envelopes agree byte for byte" \
                      || bad "ANIMUS ARMS DISAGREE on FIFO -- sh: $_oa / ps1: $_ob"
  _ra=$(cat "$_AD/a/animus-queue.xd-anim" 2>/dev/null); _rb=$(cat "$_AD/b/animus-queue.xd-anim" 2>/dev/null)
  [ "$_ra" = 'Soleil|second remark' ] && [ "$_ra" = "$_rb" ] \
    && ok "ANIMUS: both arms leave the same one-line remainder" \
    || bad "ANIMUS: remainders differ -- sh '$_ra' / ps1 '$_rb'"
  rm -f "$_AD/a/animus-queue.xd-anim" "$_AD/b/animus-queue.xd-anim"

  # the refusal: an undeclared lens is silence in both arms, and dropped
  printf 'Mallory|evil whisper\n' > "$_AD/a/animus-queue.xd-anim"
  printf 'Mallory|evil whisper\n' > "$_AD/b/animus-queue.xd-anim"
  _oa=$(_adrive sh  "$_AD/a"); _ob=$(_adrive ps1 "$_AD/b")
  if [ "$_oa" = "$_ob" ]; then
    case "$_oa" in
      *Mallory*|*'evil whisper'*) bad "ANIMUS: an undeclared lens SPOKE in both arms" ;;
      *) ok "ANIMUS: both arms refuse the undeclared lens identically" ;;
    esac
  else
    bad "ANIMUS ARMS DISAGREE on the refusal -- sh: $_oa / ps1: $_ob"
  fi
  [ ! -f "$_AD/a/animus-queue.xd-anim" ] && [ ! -f "$_AD/b/animus-queue.xd-anim" ] \
    && ok "ANIMUS: both arms drop the refused line -- no queue jam on either" \
    || bad "ANIMUS: the refused line lingers in an arm"

  # the off-switch: VOICE=0 silences both and neither touches the queue
  printf 'AntiVenom|should stay\n' > "$_AD/a/animus-queue.xd-anim"
  printf 'AntiVenom|should stay\n' > "$_AD/b/animus-queue.xd-anim"
  _oa=$(_adrive sh  "$_AD/a" ROTMOE_VOICE=0); _ob=$(_adrive ps1 "$_AD/b" ROTMOE_VOICE=0)
  case "$_oa$_ob" in *'(animus)'*) bad "ANIMUS: ROTMOE_VOICE=0 leaked a remark" ;; *) : ;; esac
  _ra=$(cat "$_AD/a/animus-queue.xd-anim" 2>/dev/null); _rb=$(cat "$_AD/b/animus-queue.xd-anim" 2>/dev/null)
  [ "$_ra" = 'AntiVenom|should stay' ] && [ "$_ra" = "$_rb" ] \
    && ok "ANIMUS: VOICE=0 -- both arms silent, both queues stand" \
    || bad "ANIMUS: VOICE=0 queue handling differs -- sh '$_ra' / ps1 '$_rb'"

  # CONTROL: the comparison must SEE a disagreement. Different remarks in,
  # different envelopes out -- or this phase proves nothing.
  printf 'Venom|sh side\n'  > "$_AD/a/animus-queue.xd-anim"
  printf 'Venom|ps1 side\n' > "$_AD/b/animus-queue.xd-anim"
  _oa=$(_adrive sh  "$_AD/a"); _ob=$(_adrive ps1 "$_AD/b")
  [ "$_oa" != "$_ob" ] && ok "CONTROL: a genuine consumption difference IS visible to this comparison" \
                       || bad "CONTROL DEAD: two different remarks read identically -- this phase proves nothing"
  rm -rf "$_AD"
else
  echo "  SKIP  no PowerShell on this machine (the animus consumption cross-diff did not run)"
  skip=$((skip+1))
fi

echo
echo "== LOCALE INVARIANCE: the same row under every installed locale =="
# The locale trap is the one defect that a numeric comparison cannot see and a
# single-locale run cannot reach. Every available comma-decimal locale is forced
# and the output must be BYTE-IDENTICAL to the C-locale output.
#
# HONEST SCOPE, measured rather than assumed: awk in the Git Bash build on the
# development machine formats %.2f in the C locale regardless of LC_ALL, so this
# phase passes there trivially and proves nothing. On a glibc runner it is a
# real test. `printf(1)` under de_DE was measured to render 0.09 as "0,00" AND
# to reject "0.09" as an invalid number -- so the hazard is genuine, it simply
# lands on a different formatter than the one the gauge uses.
base_row=$("$SH" --vector 0,0,0,0,0,0,0,0,0 --breadth 0 --M 1.05 --C 0.7 --T 0.8)
loc_tested=0
for cand in de_DE.UTF-8 de_DE.utf8 fr_FR.UTF-8 it_IT.UTF-8 nl_NL.UTF-8; do
  # `grep -c … >/dev/null`, never `grep -q`, and `locale -a` is exactly the
  # producer that makes the difference: on a glibc runner it lists hundreds of
  # entries, so `grep -q` exits long before it finishes, `locale` takes SIGPIPE,
  # and under `set -o pipefail` a SUCCESSFUL match is reported as failure.
  locale -a 2>/dev/null | grep -cix "$(printf '%s' "$cand" | tr 'A-Z' 'a-z' | sed 's/utf-8/utf8/')" >/dev/null \
    || locale -a 2>/dev/null | grep -cx "$cand" >/dev/null || continue
  loc_tested=$((loc_tested+1))
  got=$(LC_ALL="$cand" LC_NUMERIC="$cand" "$SH" --vector 0,0,0,0,0,0,0,0,0 --breadth 0 --M 1.05 --C 0.7 --T 0.8)
  [ "$got" = "$base_row" ] && ok "locale-invariant under $cand" \
    || { bad "LOCALE DRIFT under $cand"; echo "        C   : $base_row"; echo "        $cand: $got"; }
done
if [ "$loc_tested" -eq 0 ]; then
  echo "  SKIP  no alternative locale installed -- invariance UNTESTED here (not passed)"
  skip=$((skip+1))
else
  # Does this platform's awk even honour a locale? If not, say so rather than
  # letting the passes above read as a guarantee they are not.
  if [ "$(LC_ALL=de_DE.UTF-8 awk 'BEGIN{printf "%.2f",0.09}' 2>/dev/null)" = "0.09" ]; then
    echo "  NOTE  this awk ignores the locale for %.2f, so the rows above are"
    echo "        trivially green. The phase is meaningful on a glibc runner."
  fi
fi

echo
echo "== RESULT =="
echo "  $pass passed, $fail failed, $skip skipped"
# THE SKIP USED TO BE ANNOUNCED AND THEN IGNORED: the NOTE below printed "a
# SKIP is not a PASS" and the verdict line exited 0 anyway. MEASURED
# 2026-08-18 on a pwsh-less container: mutate-checker judges its per-arm
# router mutants (H01, H02) by this exit code, the fake 0 read as "checker
# stayed GREEN", and both were reported as SURVIVED -- claiming holes in a
# comparison that never ran. A real failure still outranks a skip; a skip
# outranks a pass; exit 3 is the repo's "did not run", which gate-all shows
# as "SKIP (3) -- never a pass" and no caller counts green.
if [ "$fail" -gt 0 ]; then
  echo "  R3/R13: FAIL"; exit 1
elif [ "$skip" -gt 0 ]; then
  echo "  R3/R13: SKIP (exit 3) -- the single-arm phases ran clean, but the"
  echo "  cross-diff is the point of this file, and on a machine without"
  echo "  PowerShell it did not run. A skip is never a pass."
  exit 3
else
  echo "  R3/R13: PASS"; exit 0
fi
