#!/usr/bin/env bash
# This file is part of RoT MoE.
# SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
# Copyright 2026 Saimonokuma.
#
# =============================================================================
# CROSS-DIFF, ORGAN 4 -- the two reminder arms must agree BYTE FOR BYTE.
#
# `checker/cross-diff.sh` does this for the router. This is the same instrument
# aimed at `hooks/prover-remind.sh` and `hooks/prover-remind.ps1`, and it exists
# for the same reason: a router that only fires on one operating system is a
# router for one machine, and so is a reminder.
#
# WHY --decide AND NOT THE HOOK PATH. The hook path measures the filesystem and
# git, so its output depends on the machine it runs on -- untestable as an
# equality. `--decide` takes the measurements as ARGUMENTS and reads nothing, so
# the DECISION (the part that can silently diverge between two languages) is
# comparable exactly. What --decide does not cover -- that both arms measure the
# same things off disk -- is stated in the README boundary rather than implied
# by this green.
#
# THE COMPARISON IS ON STRINGS, not on "did both produce something". A one-
# character difference in a label is a real divergence: it is what a user reads.
#
# NON-VACUITY IS ASSERTED, not assumed. The corpus must contain at least one row
# that speaks and one row that is SILENT. Without both, an arm that always
# printed -- or never did -- would pass a hundred rows of "they agree".
# =============================================================================

set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

SH="hooks/prover-remind.sh"
PS1="hooks/prover-remind.ps1"
CORPUS="checker/corpus-remind.txt"
GOLDEN="checker/golden-remind.txt"

pass=0; fail=0; skip=0
ok()  { echo "  PASS  $*"; pass=$((pass+1)); }
bad() { echo "  FAIL  $*"; [ "${GITHUB_ACTIONS:-}" = "true" ] && printf '::error title=cross-diff-remind::%s\n' "$*"; fail=$((fail+1)); }

# U1 (7.0.0): THE GOLDEN. Arm-vs-arm agreement cannot kill a SINGLE-ARM
# mutation on a machine with one arm: move a boundary in the POSIX arm on a
# pwsh-less box and nothing here compared anything -- H21/H23 sat
# INEXPRESSIBLE. The golden records the POSIX arm's expected output per
# corpus row (as a hash: byte-exact, silence-safe, and not hand-editable
# into agreement), so drift is caught with no second arm anywhere.
# REGENERATION IS A DELIBERATE ACT: `--make-golden` rewrites it from the
# CURRENT arm with a banner, so a behaviour change must be accepted on
# purpose, never absorbed silently.
_sha () {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum | cut -d' ' -f1
  else shasum -a 256 | cut -d' ' -f1; fi
}

if [ "${1:-}" = "--make-golden" ]; then
  echo "== REGENERATING THE GOLDEN -- a deliberate act =="
  echo "   Every future run holds the POSIX arm to what it prints NOW."
  {
    echo "# RoT MoE -- golden expected outputs for corpus-remind.txt (organ 4)."
    echo "# SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2"
    echo "# Copyright 2026 Saimonokuma."
    echo "# GENERATED by checker/cross-diff-remind.sh --make-golden. Never hand-edit:"
    echo "# the hash is over the POSIX arm's --decide bytes at generation time, so"
    echo "# an edit here can only make the golden LIE about what was recorded."
  } > "$GOLDEN.tmp"
  gn=0
  while read -r ev mins last debt kred ksorry alarms; do
    case "$ev" in ''|\#*) continue ;; esac
    gn=$((gn+1))
    out=$(sh "$SH" --decide "$ev" "$mins" "$last" "$debt" "$kred" "$ksorry" "$alarms" 2>/dev/null)
    orc=$?
    if [ "$orc" -ne 0 ]; then
      echo "REFUSE: row $gn exited $orc -- a golden must be cut from a healthy arm"
      rm -f "$GOLDEN.tmp"; exit 2
    fi
    printf 'row-%d sha256 %s chars %d  # %s %s %s %s %s %s %s\n' \
      "$gn" "$(printf '%s' "$out" | _sha)" "${#out}" \
      "$ev" "$mins" "$last" "$debt" "$kred" "$ksorry" "$alarms" >> "$GOLDEN.tmp"
  done < "$CORPUS"
  mv "$GOLDEN.tmp" "$GOLDEN"
  echo "   golden written: $GOLDEN ($gn rows)"
  exit 0
fi

GOLDEN_OK=''
if [ -f "$GOLDEN" ]; then
  GOLDEN_OK=1
else
  echo "  SKIP  no golden file -- single-arm drift is NOT held on this machine."
  echo "        Generate deliberately: bash checker/cross-diff-remind.sh --make-golden"
  skip=$((skip+1))
fi

echo "== cross-diff: the two reminder arms =="

[ -f "$SH" ]  || { bad "missing $SH";  echo "  cross-diff-remind: FAIL"; exit 1; }
[ -f "$PS1" ] || { bad "missing $PS1"; echo "  cross-diff-remind: FAIL"; exit 1; }
[ -f "$CORPUS" ] || { bad "missing $CORPUS"; echo "  cross-diff-remind: FAIL"; exit 1; }

PWSH=""
for c in pwsh powershell; do command -v "$c" >/dev/null 2>&1 && { PWSH="$c"; break; }; done
if [ -z "$PWSH" ]; then
  echo "  SKIP  no PowerShell on this runner -- the arms were NOT compared."
  echo "        This is a SKIP, never a PASS: an unrun comparison proves nothing."
  skip=1
fi

spoke=0; silent=0; rows=0
while read -r ev mins last debt kred ksorry alarms; do
  case "$ev" in ''|\#*) continue ;; esac
  rows=$((rows+1))
  a=$(sh "$SH" --decide "$ev" "$mins" "$last" "$debt" "$kred" "$ksorry" "$alarms" 2>/dev/null)
  arc=$?
  if [ "$arc" -ne 0 ]; then
    bad "row $rows: the POSIX arm exited $arc (it must never fail): $ev $mins $last $debt $kred $ksorry $alarms"
    continue
  fi
  if [ -n "$a" ]; then spoke=$((spoke+1)); else silent=$((silent+1)); fi

  # U1: the golden holds the POSIX arm to its recorded self, pwsh or not.
  if [ -n "$GOLDEN_OK" ]; then
    want=$(grep '^row-' "$GOLDEN" | sed -n "${rows}p" | awk '{print $3}')
    got=$(printf '%s' "$a" | _sha)
    if [ -z "$want" ]; then
      bad "row $rows has NO golden line -- the corpus grew past the golden; regenerate deliberately (--make-golden)"
    elif [ "$got" = "$want" ]; then
      ok "row $rows matches the golden ($( [ -n "$a" ] && echo "speaks ${#a} chars" || echo 'SILENT' ))"
    else
      bad "row $rows DIVERGES from the recorded golden: $ev $mins $last $debt $kred $ksorry $alarms"
      echo "        live: ${a:-<silent>}"
    fi
  fi

  if [ -n "$PWSH" ]; then
    b=$("$PWSH" -NoProfile -File "$PS1" -Decide "$ev" "$mins" "$last" "$debt" "$kred" "$ksorry" "$alarms" 2>/dev/null)
    brc=$?
    if [ "$brc" -ne 0 ]; then
      bad "row $rows: the Windows arm exited $brc: $ev $mins $last $debt $kred $ksorry $alarms"
      continue
    fi
    if [ "$a" = "$b" ]; then
      ok "row $rows agrees ($ev mins=$mins debt=$debt kred=$kred): $( [ -n "$a" ] && echo "speaks ${#a} chars" || echo 'SILENT' )"
    else
      bad "row $rows DISAGREES: $ev $mins $last $debt $kred $ksorry $alarms"
      echo "        sh : $a"
      echo "        ps1: $b"
    fi
  fi
done < "$CORPUS"

echo
echo "-- non-vacuity of the corpus --"
if [ -n "$GOLDEN_OK" ]; then
  gr=$(grep -c '^row-' "$GOLDEN")
  [ "$gr" -eq "$rows" ] && ok "golden covers all $rows rows" \
    || bad "golden has $gr rows, the corpus has $rows -- a stale golden holds nothing; regenerate deliberately"
fi
[ "$rows" -gt 0 ] && ok "corpus has $rows row(s)" || bad "corpus is EMPTY -- every comparison below is vacuous"
[ "$spoke" -gt 0 ] && ok "$spoke row(s) produce a reminder" \
  || bad "NO row produces output -- an arm that never speaks would pass this suite"
[ "$silent" -gt 0 ] && ok "$silent row(s) are SILENT (the healthy state is exercised)" \
  || bad "NO row is silent -- an arm that always speaks would pass this suite"

# --- A8/A9: the ASCII-ONLY payload contract, on the REAL hook path -----------
# WHY THIS BLOCK EXISTS, and why it is not a second copy of everything above.
# Every assertion so far drives `--decide`, and the header states that boundary
# honestly: the hook path measures the machine, so cross-arm EQUALITY is not
# testable there. ASCII-ness is a different KIND of claim -- it does not depend
# on the machine at all -- so the contract hooks/prover-remind.sh states in its
# own header ("ASCII ONLY in the emitted payload ... a non-ASCII byte under a
# legacy code page can close the JSON string early and silently kill the
# injection -- measured on the private original this is ported from") IS
# testable on the real path. Until 2026-08-22 NOTHING asserted it. The contract
# was documented and the two guards existed, but no gate would have noticed
# either guard being deleted -- the same shape as the rot-voice-gate.ps1
# encoding defect, which also passed a green suite while destroying a field.
#
# THE GUARDS BEING EXERCISED: hooks/prover-remind.sh:258 (tr -c) and
# hooks/prover-remind.ps1:382 (-replace), each at the single point every path
# leaves through.
#
# NON-VACUOUS BY CONSTRUCTION, which is the whole design of the fixture. The
# workspace below holds a .lean file whose NAME carries non-ASCII bytes and
# whose mtime is old, so the stale-proof branch quotes that name in the "last:"
# field. The bytes REACH the guard; delete the guard and they reach the payload.
# Measured while writing this: "last: Caf    Name", the non-ASCII replaced by
# spaces, 0 non-ASCII bytes in a 766-byte payload.
_ad=${TMPDIR:-/tmp}/rot-remind-ascii.$$
rm -rf "$_ad" 2>/dev/null
mkdir -p "$_ad/ws/Proofs" "$_ad/s1" "$_ad/s2" 2>/dev/null
# A Windows-shaped path for the pwsh arm: git-bash passes env vars VERBATIM, so
# a POSIX /tmp path resolves DRIVE-RELATIVE in PowerShell, the directory is not
# found, and that arm degrades quietly -- a silent skip wearing a pass's
# clothes. Cost a false finding once already; both arms get the mixed form.
_aw="$_ad"
command -v cygpath >/dev/null 2>&1 && _aw=$(cygpath -m "$_ad")
# Built with awk rather than a literal: this file stays pure ASCII itself, and
# a printf escape would not survive every transport it is edited through.
_anm=$(awk 'BEGIN{printf "Caf%c%cName", 195, 169}')
: > "$_ad/ws/Proofs/$_anm.lean"
touch -t 202601010000 "$_ad/ws/Proofs/$_anm.lean" 2>/dev/null
_apay='{"session_id":"ascii","cwd":"'"$_aw"'","hook_event_name":"UserPromptSubmit","prompt":"x"}'

_ascii_arm () {
  _al=$1; _as=$2; shift 2
  printf '%s' "$_apay" | ROTMOE_LEAN_WORKSPACE="$_aw/ws" ROTMOE_STATE_DIR="$_as" \
    CLAUDE_PLUGIN_ROOT="$REPO" "$@" > "$_ad/$_al.out" 2>"$_ad/$_al.err"
  _arc=$?
  if [ "$_arc" -ne 0 ]; then
    bad "$_al arm exited $_arc on the real hook path -- the contract is ALWAYS exit 0; a reminder must never break a build"
    return 0
  fi
  # `grep -c` prints 0 AND exits 1 when it matches nothing, so the `|| true` is
  # load-bearing and the result is validated as a number before arithmetic.
  _an=$(LC_ALL=C grep -c '[^ -~]' "$_ad/$_al.out" 2>/dev/null || true)
  case "$_an" in ''|*[!0-9]*) _an=0 ;; esac
  _ab=$(wc -c < "$_ad/$_al.out" | tr -d ' ')
  if [ "$_ab" -eq 0 ]; then
    bad "$_al arm emitted NOTHING where the fixture forces speech -- a silent arm cannot demonstrate an ASCII guard"
  elif [ "$_an" -eq 0 ]; then
    ok "$_al arm ASCII guard holds: $_ab byte payload, 0 non-ASCII, built from a module name that CARRIES non-ASCII"
  else
    bad "$_al arm: $_an line(s) carry non-ASCII -- the single-exit guard is gone; under a legacy code page this closes the JSON string early and the injection dies in silence"
  fi
}

_ascii_arm sh "$_aw/s1" sh "$SH"
if [ -n "$PWSH" ]; then
  _ascii_arm ps1 "$_aw/s2" "$PWSH" -NoProfile -File "$PS1"
else
  echo "  SKIP  no PowerShell -- the ps1 ASCII guard was NOT exercised."
fi
rm -rf "$_ad" 2>/dev/null

echo
echo "== RESULT =="
echo "  $pass passed, $fail failed, $skip skipped"
# ORDER IS THE CONTRACT: a real failure outranks a skip (a POSIX-arm corpus
# failure under a missing pwsh is still a failure), and a skip outranks a pass.
#
# THE SKIP BRANCH USED TO EXIT 0, and that was a fake green this file printed
# its own warning about: line 52 above says "This is a SKIP, never a PASS" and
# the exit code then said PASS. MEASURED 2026-08-18 on a pwsh-less container:
# checker/mutate-checker.sh judges its H21-H24 mutants by this exit code, the
# fake 0 read as "checker stayed GREEN", and four per-arm mutations were
# reported as SURVIVED -- claiming holes in a checker that was never able to
# run. Exit 3 is the repo's convention for "did not run", gate-all displays it
# as "SKIP (3) -- never a pass", and no caller counts it green.
if [ "$fail" -gt 0 ]; then
  echo "  cross-diff-remind: FAIL"; exit 1
elif [ "$skip" -gt 0 ]; then
  echo "  cross-diff-remind: SKIP (exit 3) -- the POSIX arm ran the corpus clean,"
  echo "  but the arms were NOT compared. A skip is never a pass."
  exit 3
else
  echo "  cross-diff-remind: PASS"; exit 0
fi
