#!/usr/bin/env sh
# This file is part of RoT MoE.
# SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
# Copyright 2026 Saimonokuma.
#
# R21 -- the instrument reference is GENERATED from the registry, never written.
#
# ---------------------------------------------------------------------------
# A reference work about instruments is itself an instrument, and it is subject
# to every failure this repository has already catalogued. The two that matter:
#
#   A hand-written inventory is a claim with no author. It is correct on the day
#   it is typed and silently wrong afterwards, because nothing connects it to
#   the tree it describes. So this file DERIVES the reference from
#   checker/gate-all.sh's registry and from the scripts on disk, and the default
#   run REFUSES when the committed document no longer matches what it derives.
#
#   A column is only as good as the cases that falsified it. The control column
#   below was built THREE TIMES and was wrong three times: a printf-and-the-word
#   heuristic missed controls announced through a helper; a case-sensitive match
#   on CONTROL missed spdx-sweep.sh:150, which prints lowercase; a [Cc]ontrol
#   class missed cross-diff.sh:158, which prints all-caps. Each was caught by a
#   script whose truth was already known. Both of those cases are now assertions
#   here (CONTROL 2), so the column cannot silently regress to any of the three.
#
# What this file does NOT establish, stated because the distinction is the whole
# subject: a gate carrying control text is not thereby a gate whose control ran.
# The column is STATIC EVIDENCE read off the source. It answers "does this
# instrument contain a control?" and never "did that control fire in the last
# sweep?". Only a run answers the second question, and only for that run.
# ---------------------------------------------------------------------------

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOC="$ROOT/docs/ENCYCLOPEDIA-instruments.md"
REG="$ROOT/checker/gate-all.sh"
BEGIN='<!-- ENCYCLOPEDIA:BEGIN -- generated by checker/encyclopedia.sh; edits here are overwritten -->'
END='<!-- ENCYCLOPEDIA:END -->'

WRITE=0
[ "${1:-}" = "--write" ] && WRITE=1

fails=0
passes=0
ok ()  { passes=$((passes+1)); echo "ok: $*"; }
bad () { fails=$((fails+1)); echo "FAIL: $*"; }

# --- the two derivations, as functions, so the controls exercise the code that
# --- production uses rather than a paraphrase of it -------------------------

# Rows in the DEFAULT block: between `GATES="` and its closing lone quote.
#
# THIS IS THE AUTHORITATIVE EXTRACTION, and it is copied deliberately from
# checker/gate-split.sh:56 rather than reinvented. The first version of this
# file grepped the whole source for anything shaped like a row and reported 82
# gates. The runner reports 72. The extra ten are the FULL-only block below,
# and folding them into one number does the precise thing gate-all.sh's own
# header warns about: it makes a tier that almost never runs look like part of
# every sweep. Two extractors, two counts, both printed.
registry_rows () {
  awk '/^GATES="$/{inb=1;next} inb&&/^"$/{exit} inb&&/\|/{print}' "$1"
}

# Rows appended only when MODE is full. These do NOT run in a bare sweep and do
# NOT run pre-commit. A reference that hides them is worse than no reference.
full_rows () {
  awk '/GATES="\$GATES/{inb=1;next} inb&&/^"$/{exit} inb&&/\|/{print}' "$1"
}

# CODE / COMMENT / NONE for one script. Case-insensitive on purpose: this
# corpus prints control verdicts in three different casings.
control_class () {
  _c=$(grep -icE '^[[:space:]]*[^#[:space:]].*control' "$1") || [ $? -eq 1 ]
  _m=$(grep -ic 'control' "$1") || [ $? -eq 1 ]
  if [ "$_c" -gt 0 ]; then echo CODE
  elif [ "$_m" -gt 0 ]; then echo COMMENT
  else echo NONE
  fi
}

# The instrument a row runs, or the literal command when it is not a checker.
row_instrument () {
  printf '%s' "$1" | grep -oE 'checker/[a-z0-9._-]+\.sh' || printf '%s' "$1"
}

# ---------------------------------------------------------------------------
# CONTROLS. An alarm nobody has tripped on purpose is an untested alarm, and
# every one of these three has been observed firing.
# ---------------------------------------------------------------------------

echo "--- CONTROLS ---------------------------------------------------------"

# CONTROL 1: the registry parser must be reading the registry, not a list baked
# into this file. Feed the SAME function a synthetic file and require it to see
# a row that exists nowhere in the repository.
_tmp="${TMPDIR:-/tmp}/enc-ctl-$$"
mkdir -p "$_tmp"
# The fixture has the SHAPE of the real file: a default block, a FULL-only
# block, and a row outside both that must be picked up by neither.
cat > "$_tmp/fake-registry.sh" <<'FAKEREG'
outside any block, must NOT parse|fast||bash nope.sh
GATES="
planted default gate|deep|checker/|bash checker/planted.sh
"
if [ "$MODE" = full ]; then
  GATES="$GATES
planted FULL-only gate|deep|checker/|bash checker/planted-full.sh
"
fi
FAKEREG
_pd=$(registry_rows "$_tmp/fake-registry.sh" | grep -c 'planted default gate') || [ $? -eq 1 ]
_pf=$(full_rows "$_tmp/fake-registry.sh" | grep -c 'planted FULL-only gate') || [ $? -eq 1 ]
_leak_d=$(registry_rows "$_tmp/fake-registry.sh" | grep -c 'FULL-only\|must NOT parse') || [ $? -eq 1 ]
_leak_f=$(full_rows "$_tmp/fake-registry.sh" | grep -c 'planted default gate\|must NOT parse') || [ $? -eq 1 ]
if [ "$_pd" -eq 1 ] && [ "$_pf" -eq 1 ] && [ "$_leak_d" -eq 0 ] && [ "$_leak_f" -eq 0 ]; then
  ok "CONTROL 1: both extractors read the file given, and neither sees the other's rows"
else
  bad "CONTROL 1 DEAD: default=$_pd full=$_pf leak_into_default=$_leak_d leak_into_full=$_leak_f"
  echo "      The two scopes are not separated, so the counts below conflate a tier"
  echo "      that runs on every commit with one that runs almost never."
fi

# CONTROL 2: the control column must separate a script that has a control from
# one that does not, and must survive BOTH casings that already broke it once.
cat > "$_tmp/no-control.sh" <<'NOCTL'
#!/usr/bin/env sh
echo "this script checks nothing and says nothing about its own falsifiability"
NOCTL
cat > "$_tmp/upper-control.sh" <<'UPPERCTL'
#!/usr/bin/env sh
ok "CONTROL: an all-caps announcement, the casing cross-diff.sh uses"
UPPERCTL
cat > "$_tmp/lower-control.sh" <<'LOWERCTL'
#!/usr/bin/env sh
echo "control OK: a lowercase announcement, the casing spdx-sweep.sh uses"
LOWERCTL
_none=$(control_class "$_tmp/no-control.sh")
_up=$(control_class "$_tmp/upper-control.sh")
_low=$(control_class "$_tmp/lower-control.sh")
_real_up=$(control_class "$ROOT/checker/cross-diff.sh")
_real_low=$(control_class "$ROOT/checker/spdx-sweep.sh")
if [ "$_none" = NONE ] && [ "$_up" = CODE ] && [ "$_low" = CODE ] \
   && [ "$_real_up" = CODE ] && [ "$_real_low" = CODE ]; then
  ok "CONTROL 2: the column discriminates, in both casings, on synthetic AND real cases"
else
  bad "CONTROL 2 DEAD: none=$_none upper=$_up lower=$_low cross-diff=$_real_up spdx=$_real_low"
  echo "      A column that cannot separate these five cases classifies nothing."
fi

# ---------------------------------------------------------------------------
# The reference itself.
# ---------------------------------------------------------------------------

render_region () {
  _rows=$(registry_rows "$REG")
  _frows=$(full_rows "$REG")
  _nrows=$(printf '%s\n' "$_rows" | grep -c .) || [ $? -eq 1 ]
  _nfull=$(printf '%s\n' "$_frows" | grep -c .) || [ $? -eq 1 ]
  _nfast=$(printf '%s\n' "$_rows" | awk -F'|' '$2=="fast"' | grep -c .) || [ $? -eq 1 ]
  _ndeep=$(printf '%s\n' "$_rows" | awk -F'|' '$2=="deep"' | grep -c .) || [ $? -eq 1 ]
  _nscripts=$(ls -1 "$ROOT"/checker/*.sh | grep -c .) || [ $? -eq 1 ]

  _ccode=0; _ccomment=0; _cnone=0
  for _f in "$ROOT"/checker/*.sh; do
    case "$(control_class "$_f")" in
      CODE) _ccode=$((_ccode+1)) ;;
      COMMENT) _ccomment=$((_ccomment+1)) ;;
      NONE) _cnone=$((_cnone+1)) ;;
    esac
  done

  # Scripts on disk that no registry row runs. BOTH blocks count here: a script
  # reachable only under --full is wired, however rarely it fires.
  { printf '%s\n' "$_rows"; printf '%s\n' "$_frows"; } | awk -F'|' '{print $4}' \
    | grep -oE 'checker/[a-z0-9._-]+\.sh' | sort -u > "$_tmp/referenced.txt"
  (cd "$ROOT" && ls -1 checker/*.sh) | sort > "$_tmp/ondisk.txt"
  _unrun=$(comm -23 "$_tmp/ondisk.txt" "$_tmp/referenced.txt")
  _nunrun=$(printf '%s\n' "$_unrun" | grep -c .) || [ $? -eq 1 ]
  _missing=$(comm -13 "$_tmp/ondisk.txt" "$_tmp/referenced.txt")
  _nmissing=$(printf '%s\n' "$_missing" | grep -c .) || [ $? -eq 1 ]

  echo "$BEGIN"
  echo
  echo "## Digest"
  echo
  echo "Regenerate with \`sh checker/encyclopedia.sh --write\`. A bare run compares"
  echo "this section against the tree and exits 1 when they have drifted apart."
  echo
  echo "| Measure | Value |"
  echo "|---|---|"
  echo "| Gates in the DEFAULT table (a bare sweep runs these) | $_nrows |"
  echo "| Of those, fast tier | $_nfast |"
  echo "| Of those, deep tier | $_ndeep |"
  echo "| Gates reachable ONLY under --full | $_nfull |"
  echo "| Checker scripts on disk | $_nscripts |"
  echo "| Scripts no registry row runs | $_nunrun |"
  echo "| Registry rows naming a missing script | $_nmissing |"
  echo "| Scripts with control text in CODE | $_ccode |"
  echo "| Scripts with control text only in COMMENTS | $_ccomment |"
  echo "| Scripts with no control text at all | $_cnone |"
  echo
  echo "The last three columns are STATIC EVIDENCE. They report what the source"
  echo "contains, never what ran. A gate whose control text is present may still"
  echo "have a control that never executes, and this document cannot tell you so."
  echo
  echo "### The FULL-only tier"
  echo
  echo "These $_nfull gates are appended to the table only when the runner is in"
  echo "full mode. A bare sweep does not run them and no commit ever triggers"
  echo "them. They are listed separately because a total that folds them in"
  echo "reports a suite larger than the one that actually guards a commit --"
  echo "which is the failure \`checker/gate-all.sh\`'s own header describes, where"
  echo "a gate sat behind a flag, was red, and the default sweep printed green."
  echo
  if [ "$_nfull" -eq 0 ]; then
    echo "None. If this reads None and the runner still has a full mode, the"
    echo "extractor has stopped seeing that block -- treat it as broken, not empty."
  else
    printf '%s\n' "$_frows" | while IFS='|' read -r _fn _ft _ftr _fc; do
      [ -n "$_fn" ] && echo "- $_fn"
    done
  fi
  echo
  echo "### Scripts no registry row runs"
  echo
  if [ "$_nunrun" -eq 0 ]; then
    echo "None."
  else
    printf '%s\n' "$_unrun" | while IFS= read -r _u; do
      [ -n "$_u" ] && echo "- \`$_u\`"
    done
  fi
  echo
  echo "### Scripts whose control text is only in comments, or absent"
  echo
  for _f in "$ROOT"/checker/*.sh; do
    _cls=$(control_class "$_f")
    case "$_cls" in
      COMMENT) echo "- \`checker/$(basename "$_f")\` -- COMMENT only" ;;
      NONE)    echo "- \`checker/$(basename "$_f")\` -- no control text" ;;
    esac
  done
  echo
  echo "## A. The gates, in registry order"
  echo
  echo "| # | Gate | Tier | Runs when | Instrument | Control text |"
  echo "|---|---|---|---|---|---|"
  _i=0
  printf '%s\n' "$_rows" | while IFS='|' read -r _name _tier _trigs _cmd; do
    _i=$((_i+1))
    _inst=$(row_instrument "$_cmd")
    if [ -f "$ROOT/$_inst" ]; then
      _cls=$(control_class "$ROOT/$_inst")
    else
      _cls="n/a"
    fi
    if [ -z "$_trigs" ]; then _when="always"; else _when="$_trigs"; fi
    echo "| $_i | $_name | $_tier | $_when | \`$_inst\` | $_cls |"
  done
  echo
  echo "$END"
}

# ---------------------------------------------------------------------------
# Write, or refuse.
# ---------------------------------------------------------------------------

echo
echo "--- REFERENCE --------------------------------------------------------"

if [ ! -f "$DOC" ]; then
  bad "the reference document does not exist at docs/ENCYCLOPEDIA-instruments.md"
  echo "      Run: sh checker/encyclopedia.sh --write"
  rm -rf "$_tmp"
  exit 1
fi

render_region > "$_tmp/fresh.txt"

# The committed region, between the markers.
awk -v b="$BEGIN" -v e="$END" '
  $0 == b {inside=1}
  inside {print}
  $0 == e {inside=0}
' "$DOC" > "$_tmp/committed.txt"

_ncommitted=$(grep -c . "$_tmp/committed.txt") || [ $? -eq 1 ]

# CONTROL 3: the comparison must be able to REFUSE. Mutate a copy of the freshly
# rendered region and require the same comparison to report it as drifted.
# Tamper the FIRST numeric table cell, whatever it happens to be named.
#
# The previous form substituted one row BY NAME. Renaming that row -- which
# happened in this file's first hour, when the digest learned to separate the
# default table from the FULL-only one -- made the pattern match nothing, so
# the tampered copy was byte-identical to the true one and the control
# reported itself DEAD. It was right to. A control anchored on a string that
# the thing it guards is free to change is a control with an expiry date
# nobody wrote down.
sed '0,/| [0-9][0-9]* |/s/| [0-9][0-9]* |/| 9999 |/' "$_tmp/fresh.txt" > "$_tmp/tampered.txt"
if diff -q "$_tmp/fresh.txt" "$_tmp/tampered.txt" >/dev/null 2>&1; then
  bad "CONTROL 3 DEAD: a tampered region compared EQUAL to the true one."
  echo "      This comparison cannot refuse anything, so its green means nothing."
else
  ok "CONTROL 3: a tampered region IS reported as drifted"
fi

if [ "$WRITE" -eq 1 ]; then
  if [ "$_ncommitted" -eq 0 ]; then
    bad "the document has no ENCYCLOPEDIA:BEGIN / END markers to write between"
    rm -rf "$_tmp"
    exit 1
  fi
  awk -v b="$BEGIN" -v e="$END" -v f="$_tmp/fresh.txt" '
    $0 == b {while ((getline line < f) > 0) print line; skip=1; next}
    $0 == e {skip=0; next}
    !skip {print}
  ' "$DOC" > "$_tmp/newdoc.md"
  cp "$_tmp/newdoc.md" "$DOC"
  ok "reference regenerated into docs/ENCYCLOPEDIA-instruments.md"
else
  if [ "$_ncommitted" -eq 0 ]; then
    bad "the document has no ENCYCLOPEDIA:BEGIN / END markers -- nothing is derived"
  elif diff -u "$_tmp/committed.txt" "$_tmp/fresh.txt" > "$_tmp/drift.txt" 2>&1; then
    ok "the committed reference matches the tree it describes"
  else
    bad "the committed reference has DRIFTED from the tree."
    echo "      A reference that no longer describes the repository is worse than none:"
    echo "      it is read as current. Regenerate with: sh checker/encyclopedia.sh --write"
    head -25 "$_tmp/drift.txt" | sed 's/^/      /'
  fi
fi

rm -rf "$_tmp"

echo
echo "$passes passed, $fails failed"
[ "$fails" -eq 0 ] || exit 1
exit 0
