#!/usr/bin/env bash
# This file is part of RoT MoE.
# SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
# Copyright 2026 Saimonokuma.
# =============================================================================
# FACTS BLOCK -- the numbers on the README page, recomputed from the tree.
#
# WHY THIS EXISTS
#   A count typed into prose is a snapshot. It is true on the day it is written
#   and silently false afterwards, and nothing on the page can tell the reader
#   which day that was. This repo has already been bitten by exactly that: two
#   millisecond figures sat in a table until they had drifted 3x before anyone
#   noticed, and a hand-written module count went stale the moment a module was
#   added.
#
#   So the counts live in a GENERATED region of README.md, between
#   <!-- FACTS:BEGIN --> and <!-- FACTS:END -->, and this checker regenerates
#   them and fails the build if the page disagrees with the tree. The page
#   cannot drift, because drifting is a red build.
#
# WHAT IS AND IS NOT IN HERE
#   Every row is computed by a command that is printed BESIDE the number, so a
#   reader can re-run it. A fact whose canonical count I could not establish is
#   OMITTED rather than guessed:
#
#   - The theorem count comes from checker/count-theorems.sh, NOT from a bare
#     grep. Measured 2026-08-12: a bare `grep -c '^\s*(theorem|lemma)'` says
#     1589, the canonical counter says 1566. The counter rejects prose and
#     comment matches; the grep does not. The looser number would have been
#     wrong by 23 and would have looked authoritative.
#   - The GATE count is deliberately ABSENT. gate-all.sh's table has 72 rows
#     matching the row shape, while the runner reports 62 shipped gates; the
#     difference is a filter I did not chase, and publishing 72 beside a runner
#     that prints 62 would have manufactured the exact contradiction this file
#     exists to prevent. Better a missing row than a confident wrong one.
#
# USAGE
#   bash checker/facts-block.sh            verify README matches the tree
#   bash checker/facts-block.sh --emit     print the block (to paste in)
#   bash checker/facts-block.sh --write    rewrite the block in README.md
#
# EXITS  0 pass | 1 README disagrees with the tree, or markers missing | 2 tooling
# =============================================================================

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 2

README="README.md"
BEGIN='<!-- FACTS:BEGIN -- generated by checker/facts-block.sh; do not hand-edit -->'
END='<!-- FACTS:END -->'

pass=0; fail=0
ok  () { printf '  PASS  %s\n' "$1"; pass=$((pass+1)); }
bad () { printf '  FAIL  %s\n' "$1"; fail=$((fail+1)); }
inf () { printf '  ----  %s\n' "$1"; }

# --- REFUSAL: a count over zero files is not a measurement of zero -----------
[ -f "$README" ] || { echo "facts-block: no README.md at $REPO_ROOT"; exit 2; }
[ -d lean/Proofs ] || { echo "facts-block: no lean/Proofs -- refusing to publish zeroes"; exit 2; }

# --- THE FACTS ---------------------------------------------------------------
f_modules ()  { ls lean/Proofs/*.lean 2>/dev/null | wc -l | tr -d ' '; }
f_theorems () { bash checker/count-theorems.sh lean/Proofs/*.lean 2>/dev/null | tail -1 | tr -d ' '; }
f_mutants ()  { ls lean/mutate/mutate_*.sh 2>/dev/null | wc -l | tr -d ' '; }
f_checkers () { ls checker/*.sh 2>/dev/null | wc -l | tr -d ' '; }
f_hooks ()    { node -e 'const fs=require("fs");const j=JSON.parse(fs.readFileSync("hooks/hooks.json","utf8").replace(/^﻿/,""));const h=j.hooks||j;console.log(Object.keys(h).length);' 2>/dev/null; }

emit_block () {
  local m t x c k
  m="$(f_modules)"; t="$(f_theorems)"; x="$(f_mutants)"; c="$(f_checkers)"; k="$(f_hooks)"
  # A blank or zero anywhere means the measurement did not happen. Publishing a
  # zero as if it were a finding is the failure mode this whole repo is about.
  for v in "$m" "$t" "$x" "$c" "$k"; do
    case "$v" in ''|0) echo "facts-block: a fact measured empty or zero -- refusing to emit" >&2; return 3 ;; esac
  done
  printf '%s\n' "$BEGIN"
  printf '%s\n' ''
  printf '%s\n' '| what | how many | recomputed by |'
  printf '%s\n' '|---|---|---|'
  printf '| Lean modules in `lean/Proofs/` | **%s** | `ls lean/Proofs/*.lean \| wc -l` |\n' "$m"
  printf '| theorems and lemmas proved | **%s** | `bash checker/count-theorems.sh lean/Proofs/*.lean` |\n' "$t"
  printf '| mutation suites | **%s** | `ls lean/mutate/mutate_*.sh \| wc -l` |\n' "$x"
  printf '| checkers | **%s** | `ls checker/*.sh \| wc -l` |\n' "$c"
  printf '| hook events wired by the plugin | **%s** | keys of `hooks/hooks.json` |\n' "$k"
  printf '%s\n' ''
  printf '%s\n' 'Every number above is regenerated by `checker/facts-block.sh` and the build'
  printf '%s\n' 'fails if this page disagrees with the tree, so none of them can go stale'
  printf '%s\n' 'quietly. The theorem count is the canonical counter, which rejects prose --'
  printf '%s\n' 'a bare grep over the same files reports 23 more.'
  printf '%s\n' ''
  printf '%s\n' "$END"
}

extract_block () {  # <file> -> the block as it currently stands
  awk -v b="$BEGIN" -v e="$END" '
    $0 == b {inb=1} inb {print} $0 == e {inb=0}' "$1"
}

case "${1:-}" in
  --emit) emit_block; exit $? ;;
  --write)
    tmp="$(mktemp)" || exit 2
    blk="$(mktemp)" || exit 2
    emit_block > "$blk" || { rm -f "$tmp" "$blk"; exit 3; }
    if grep -qF "$BEGIN" "$README"; then
      # The block goes through a FILE, never through `awk -v`. Measured
      # 2026-08-12: passing it as a -v variable made awk interpret the markdown
      # escape `\|` as a plain `|`, which broke the table AND left the written
      # block permanently unequal to the generated one -- the writer produced a
      # file its own verifier rejected. awk -v processes escape sequences; a
      # getline from a file does not.
      awk -v b="$BEGIN" -v e="$END" -v bf="$blk" '
        $0 == b {while ((getline ln < bf) > 0) print ln; close(bf); skip=1; next}
        $0 == e {skip=0; next}
        !skip {print}' "$README" > "$tmp" && mv "$tmp" "$README"
      rm -f "$blk"
      echo "facts-block: block rewritten in place"
    else
      echo "facts-block: no FACTS markers in README -- add them first" >&2; rm -f "$tmp" "$blk"; exit 1
    fi
    exit 0 ;;
esac

echo "== facts block: the README's counts against the tree"

if ! grep -qF "$BEGIN" "$README" || ! grep -qF "$END" "$README"; then
  bad "README.md has no FACTS:BEGIN/FACTS:END block -- the counts are unguarded prose"
  echo "== facts-block: $pass passed, $fail failed"
  exit 1
fi
ok "README.md carries a FACTS block with both markers"

fresh="$(emit_block)" || { echo "facts-block: could not measure the tree"; exit 2; }
current="$(extract_block "$README")"

if [ "$fresh" = "$current" ]; then
  ok "every published count matches the tree it describes"
else
  bad "the FACTS block is STALE -- README disagrees with the tree"
  inf "run: bash checker/facts-block.sh --write"
  diff <(printf '%s\n' "$current") <(printf '%s\n' "$fresh") | head -20
fi

# --- CONTROLS: an instrument that cannot fail proves nothing -----------------
# C1: a single corrupted digit must be caught.
#
# PORTABILITY DEFECT, CAUGHT BY macOS CI AND NOT BY ANY LOCAL RUN. This was
# `sed '0,/\*\*[0-9]/s//**9999/'`. The `0,/re/` address is a GNU extension:
# GNU sed treats it as "from the start until the first match", BSD sed (macOS)
# has no line 0, so the range NEVER matches, the corruption never lands, and
# the control compared the block against an identical copy of itself.
#
# The failure mode is worth naming because it is the good one: the control
# reported ITSELF blind rather than reporting the instrument sound. It said
# "corrupting a count changed nothing", which is exactly true -- on that
# platform nothing had been corrupted. A control that fails when it cannot
# corrupt is doing its job; one that passed here would have certified a
# comparison nobody had tested.
#
# Replaced with awk, which is portable, and the corruption is now ASSERTED to
# have landed rather than inferred from a difference -- an empty `_c1` from a
# sed that errored would also "differ", and would have read as a pass.
_c1="$(printf '%s\n' "$fresh" | awk '!d && sub(/\*\*[0-9]+\*\*/, "**9999**") { d=1 } { print }')"
# `case`, not `printf | grep -q`. The repo's own lint caught the first draft:
# piping into `grep -q` under `set -o pipefail` makes the exit status depend on
# whether grep exits early and SIGPIPEs the writer (141), which differs between
# platforms. A case-glob answers the same question with no pipe and no fork.
case $_c1 in
  *'**9999**'*)
    if [ "$_c1" != "$fresh" ]; then ok "CONTROL: a corrupted count differs from the truth (the comparison can fail)"
    else bad "CONTROL: corrupting a count changed nothing -- the comparison is blind"; fi ;;
  *)
    bad "CONTROL: the corruption did NOT LAND -- this control tested nothing, which is not the same as the comparison being sound" ;;
esac

# C2: a README with the markers stripped must be rejected.
_c2="$(mktemp)"; grep -vF "$BEGIN" "$README" > "$_c2"
if grep -qF "$BEGIN" "$_c2"; then bad "CONTROL: the marker check is blind"; else ok "CONTROL: a README missing the BEGIN marker IS detectable"; fi
rm -f "$_c2"

# C3: the canonical theorem counter must disagree with a naive grep -- if they
# ever agree, the counter has stopped rejecting prose and this row is unguarded.
_naive=$(grep -chE '^[[:space:]]*(theorem|lemma) ' lean/Proofs/*.lean 2>/dev/null | awk '{s+=$1} END{print s+0}')
_canon=$(f_theorems)
if [ "$_naive" != "$_canon" ]; then
  ok "CONTROL: the canonical counter still rejects what a bare grep accepts (${_canon} vs ${_naive})"
else
  bad "CONTROL: canonical counter and naive grep now agree (${_canon}) -- the counter may have stopped filtering"
fi

echo "== facts-block: $pass passed, $fail failed"
[ "$fail" -eq 0 ] || exit 1
exit 0
