#!/usr/bin/env bash
# This file is part of RoT MoE.
# SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
# Copyright 2026 Saimonokuma.
#
# =============================================================================
# BUILD THE TWO RELEASE ARTIFACTS -- AND REFUSE TO SHIP A DISHONEST ONE.
#
# Two zips, from one tree:
#
#   rot-moe-<ver>-core.zip       the plugin. NO Lean, NO installer, NO network.
#   rot-moe-<ver>-lean.zip       the same plugin PLUS the opt-in Lean fetcher
#                                and the proof corpus.
#
# WHY THIS IS A CHECKER AND NOT A BUILD SCRIPT. The Core artifact carries a
# promise in its own README -- "no network, ever" -- and a promise a machine
# does not check is a promise that survives exactly until someone adds a file.
# If SETUP_LEAN ever lands in the Core zip, that sentence becomes false and the
# reader has no way to know. So every claim the two artifacts make about
# themselves is asserted HERE, against the zip that will actually be uploaded,
# and this file exits non-zero rather than emit one that lies.
#
# The version is READ from .claude-plugin/plugin.json. It is never passed in:
# an argument would let the zip name and the manifest inside it disagree, which
# is the whole class of defect release-consistency.sh exists to prevent.
#
# Exit: 0 both artifacts built and every assertion held · 1 an assertion FAILED
#       (nothing is uploaded) · 2 refuse (a tool is missing) · 3 SKIP.
# =============================================================================

set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

PASS=0; FAIL=0
ok  () { printf '  PASS  %s\n' "$*"; PASS=$((PASS+1)); }
bad () { printf '  FAIL  %s\n' "$*"; FAIL=$((FAIL+1)); }
note() { printf '  ----  %s\n' "$*"; }

command -v zip   >/dev/null 2>&1 || { echo "REFUSE: zip absent";   exit 2; }
command -v unzip >/dev/null 2>&1 || { echo "REFUSE: unzip absent"; exit 2; }

MANIFEST=".claude-plugin/plugin.json"
[ -f "$MANIFEST" ] || { echo "REFUSE: $MANIFEST missing"; exit 2; }
VER=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$MANIFEST" | head -1)
case "$VER" in
  [0-9]*.[0-9]*.[0-9]*) : ;;
  *) echo "REFUSE: could not read a semver version from $MANIFEST (got '$VER')"; exit 2 ;;
esac

OUT="${ROTMOE_RELEASE_DIR:-$REPO/.release}"
rm -rf "$OUT"; mkdir -p "$OUT"
CORE="$OUT/rot-moe-$VER-core.zip"
LEAN="$OUT/rot-moe-$VER-lean.zip"

echo "== release package :: version $VER =="
note "output directory: $OUT"

# --- what belongs in each artifact -------------------------------------------
# CORE is what a user installs to get the router. It is deliberately a SUBSET:
# a marketplace reader downloading "core" and finding a proof corpus and a
# multi-gigabyte fetcher inside would be right to feel misled.
CORE_PATHS="
.claude-plugin
hooks
agents
engine
ARM_ROUTER.sh
ARM_ROUTER.ps1
DISARM_ROUTER.sh
DISARM_ROUTER.ps1
README.md
NOTICE.md
LICENSE
LICENSE-EUPL-1.2
LICENSES
SECURITY.md
CONTRIBUTING.md
CODE_OF_CONDUCT.md
CITATION.cff
CLAUDE.md
"
# LEAN adds the two things that make re-verification possible, and nothing else.
LEAN_EXTRA="
SETUP_LEAN.sh
SETUP_LEAN.ps1
lean
checker
"

missing=0
for p in $CORE_PATHS $LEAN_EXTRA; do
  [ -e "$p" ] || { bad "declared for packaging but not on disk: $p"; missing=$((missing+1)); }
done
[ "$missing" -eq 0 ] && ok "every declared path exists on disk"

# --- build --------------------------------------------------------------------
# -x excludes build output: .lake is measured in gigabytes and is regenerated by
# lake, so shipping it would be both enormous and stale on arrival.
zip -q -r "$CORE" $CORE_PATHS -x '*/.lake/*' '*/.git/*' >/dev/null 2>&1
zrc=$?
[ "$zrc" -eq 0 ] && [ -s "$CORE" ] || bad "core zip did not build (zip exit $zrc)"

zip -q -r "$LEAN" $CORE_PATHS $LEAN_EXTRA -x '*/.lake/*' '*/.git/*' '*.olean' >/dev/null 2>&1
zrc=$?
[ "$zrc" -eq 0 ] && [ -s "$LEAN" ] || bad "lean zip did not build (zip exit $zrc)"

[ -s "$CORE" ] && note "core: $(wc -c < "$CORE" | tr -d ' ') bytes"
[ -s "$LEAN" ] && note "lean: $(wc -c < "$LEAN" | tr -d ' ') bytes"

# MATERIALISE the listing, never pipe it into `grep -q`.
# `set -o pipefail` is on, and `grep -q` exits at the first match -- which hands
# `unzip` a SIGPIPE and makes the PIPELINE status non-zero even though the match
# SUCCEEDED. Measured here: the lean artifact was reported as "missing
# SETUP_LEAN.sh" while the file was demonstrably inside it. checker/portability.sh
# forbids this shape repo-wide for the same reason; this file had to learn it.
LST_CORE="$OUT/.list-core"; LST_LEAN="$OUT/.list-lean"
list_to () { unzip -Z1 "$1" > "$2" 2>/dev/null; }
has () { grep -q "$2" "$1"; }

[ -s "$CORE" ] && list_to "$CORE" "$LST_CORE"
[ -s "$LEAN" ] && list_to "$LEAN" "$LST_LEAN"


# --- 1. THE CORE ARTIFACT MUST NOT BE ABLE TO REACH THE NETWORK --------------
# This is the assertion that earns the promise in the README. It is stated as a
# property of the ZIP, not of the tree, because the zip is what a stranger runs.
if [ -s "$CORE" ]; then
  leak=0
  for forbidden in SETUP_LEAN.sh SETUP_LEAN.ps1; do
    if has "$LST_CORE" "^$forbidden$"; then
      bad "the CORE artifact contains $forbidden -- its 'no network' promise is FALSE"
      leak=$((leak+1))
    fi
  done
  if has "$LST_CORE" '^lean/'; then
    bad "the CORE artifact contains the lean/ corpus -- it is not the core artifact"
    leak=$((leak+1))
  fi
  [ "$leak" -eq 0 ] && ok "CORE carries no Lean fetcher and no proof corpus -- it cannot download anything"
fi

# --- 2. THE LEAN ARTIFACT MUST ACTUALLY CARRY WHAT ITS NAME SELLS ------------
# The opposite failure, and just as bad: a "with Lean" download that cannot
# verify anything.
if [ -s "$LEAN" ]; then
  short=0
  for needed in SETUP_LEAN.sh SETUP_LEAN.ps1; do
    has "$LST_LEAN" "^$needed$" || { bad "the LEAN artifact is missing $needed"; short=$((short+1)); }
  done
  for needed in lean/lakefile.toml lean/lean-toolchain; do
    has "$LST_LEAN" "^$needed$" || { bad "the LEAN artifact is missing $needed"; short=$((short+1)); }
  done
  nmod=$(grep -c '^lean/Proofs/.*\.lean$' "$LST_LEAN" || true)
  ondisk=$(find lean/Proofs -name '*.lean' | grep -c . || true)
  if [ "$nmod" -ne "$ondisk" ]; then
    bad "the LEAN artifact carries $nmod proof module(s) but $ondisk are on disk"
    short=$((short+1))
  fi
  [ "$short" -eq 0 ] && ok "LEAN carries both fetchers, the lakefile, the pinned toolchain and all $nmod proof module(s)"
fi

# --- 3. NEITHER MAY CARRY BUILD OUTPUT OR HISTORY ----------------------------
# .lake was measured at 7.2 GB on the machine this was written on, and an .olean
# is a per-toolchain binary that is stale the moment lean-toolchain moves.
for z in "$CORE" "$LEAN"; do
  [ -s "$z" ] || continue
  zl="$OUT/.list-tmp"; list_to "$z" "$zl"
  junk=$(grep -cE '(^|/)\.lake/|\.olean$|(^|/)\.git/' "$zl" || true)
  if [ "$junk" -gt 0 ]; then
    bad "$(basename "$z") carries $junk build-output or history entr(ies)"
  else
    ok "$(basename "$z") carries no .lake, no .olean, no .git"
  fi
done

# --- 4. THE VERSION INSIDE MUST BE THE VERSION ON THE BOX --------------------
# A zip named 0.1.0 containing a manifest that says something else is the exact
# drift release-consistency.sh gates in the tree; it has to hold in the artifact
# too, or the gate only covers the copy nobody downloads.
for z in "$CORE" "$LEAN"; do
  [ -s "$z" ] || continue
  inner=$(unzip -p "$z" ".claude-plugin/plugin.json" 2>/dev/null \
          | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
  if [ "$inner" = "$VER" ]; then
    ok "$(basename "$z") declares version $inner inside, matching its name"
  else
    bad "$(basename "$z") is named for $VER but its manifest says '$inner'"
  fi
done

# --- 5. RELEASE.md MUST DESCRIBE THE ARTIFACTS THAT WERE ACTUALLY BUILT ------
# A release page is the first thing a stranger reads and the last thing anyone
# re-checks. If it names a filename that no longer exists, or a version that was
# bumped without it, the download instructions are wrong for everyone who
# follows them -- and nothing in the repository would ever say so.
#
# What is deliberately NOT asserted here: the byte size and the gate count. Both
# are true today and false after the next commit; pinning either would turn a
# correct release page red and invite the next maintainer to delete the check.
# The page states the size as a BOUND ("well under a megabyte") and that bound
# IS asserted below, because a bound survives a change that a snapshot does not.
RMD="RELEASE.md"
if [ ! -f "$RMD" ]; then
  bad "$RMD is missing -- the release has no page to point a downloader at"
else
  rmd_fail=0
  # the exact asset filenames this run produced
  for z in "$CORE" "$LEAN"; do
    [ -s "$z" ] || continue
    n=$(basename "$z")
    grep -qF -- "$n" "$RMD" || { rmd_fail=1; note "$RMD does not name the asset $n"; }
  done
  # the version being built
  grep -qF -- "$VER" "$RMD" || { rmd_fail=1; note "$RMD does not mention version $VER"; }
  # the promise that assertion 1 enforces must actually be made on the page,
  # otherwise the check guards a claim nobody reads
  grep -qiF -- "no network" "$RMD" || { rmd_fail=1; note "$RMD does not carry the no-network claim that assertion 1 enforces"; }
  if [ "$rmd_fail" -eq 0 ]; then
    ok "$RMD names both assets, version $VER, and the claim this script enforces"
  else
    bad "$RMD has drifted from the artifacts -- move them in the same edit"
  fi

  # the size BOUND the page states, asserted against the artifact
  if [ -s "$CORE" ]; then
    cb=$(wc -c < "$CORE" | tr -d ' ')
    if [ "$cb" -lt 1048576 ]; then
      ok "CORE is $cb bytes -- under the 1 MB the page claims"
    else
      bad "CORE is $cb bytes, over 1 MB -- $RMD says 'well under a megabyte' and is now FALSE"
    fi
  fi
fi

# --- negative controls --------------------------------------------------------
# Every assertion above is worth exactly as much as its ability to fail.
echo
echo "-- negative controls --"

# C1: plant SETUP_LEAN.sh into a COPY of the core zip; assertion 1 must catch it.
if [ -s "$CORE" ]; then
  probe="$OUT/probe-core.zip"
  cp "$CORE" "$probe"
  ( cd "$REPO" && zip -q "$probe" SETUP_LEAN.sh >/dev/null 2>&1 )
  prc=$?
  plist="$OUT/.list-probe"; list_to "$probe" "$plist"
  if [ "$prc" -ne 0 ]; then
    bad "CONTROL DID NOT APPLY: could not plant SETUP_LEAN.sh (zip exit $prc) -- discarded, NOT survived"
  elif ! has "$plist" '^SETUP_LEAN.sh$'; then
    bad "CONTROL DID NOT APPLY: the planted file is not in the probe -- discarded, NOT survived"
  else
    ok "CONTROL: a core zip with SETUP_LEAN.sh planted IS detectable -- assertion 1 can fire"
  fi
  rm -f "$probe"
fi

# C2: the predicate must not fire on the real core zip, or it is always-fail and
# proves nothing about the artifact we are actually shipping.
if [ -s "$CORE" ]; then
  if has "$LST_CORE" '^SETUP_LEAN.sh$'; then
    bad "CONTROL: the real core zip trips the predicate -- it is always-fail"
  else
    ok "CONTROL: the real core zip does NOT trip it -- the check discriminates"
  fi
fi

# C4: strip the asset name from a COPY of RELEASE.md; the predicate must notice.
if [ -f "$RMD" ] && [ -s "$CORE" ]; then
  rprobe="$OUT/probe-release.md"
  sed "s|$(basename "$CORE")|REMOVED|g" "$RMD" > "$rprobe"; rrc=$?
  if [ "$rrc" -ne 0 ] || [ ! -s "$rprobe" ]; then
    bad "CONTROL DID NOT APPLY: sed exit $rrc / empty probe -- discarded, NOT survived"
  elif cmp -s "$rprobe" "$RMD"; then
    bad "CONTROL DID NOT APPLY: the probe is identical to $RMD -- discarded, NOT survived"
  elif grep -qF -- "$(basename "$CORE")" "$rprobe"; then
    bad "CONTROL: a page with the asset name removed still passed -- the check is blind"
  else
    ok "CONTROL: a page missing the asset name IS detected -- assertion 5 can fire"
  fi
  rm -f "$rprobe"
fi

# C3: a version mismatch must be visible. Rewriting a file inside a zip is more
# machinery than this needs; comparing the two strings directly proves the
# comparison itself is real.
if [ "$VER" = "0.0.0-not-a-real-version" ]; then
  bad "CONTROL DEAD: the sentinel compares equal to the real version"
else
  ok "CONTROL: a wrong version string IS distinguishable from $VER"
fi

printf '\n== release package: %d passed, %d failed\n' "$PASS" "$FAIL"
if [ "$FAIL" -ne 0 ]; then
  echo "   NOTHING IS UPLOADED. Fix the artifact, not the assertion."
  exit 1
fi
echo "   artifacts ready:"
echo "     $CORE"
echo "     $LEAN"
exit 0
